#! /usr/bin/env python3.8
# -*- coding: utf-8 -*-



correlated_groups={}

correlated_groups["lin_eq_features_groups"]=[["deltaZPE","deltaE","deltaG"],
                                            # ["SMD-solv"],
                                            # ["expl1wat"]
                                            ]

correlated_groups["eq_features_groups"]=[["SMD-solv"],["expl1wat"],
                                         ["RDG%HB"],["RDG%VdW"],["RDG%st"],
                                         ["prom-RDG%HB"],["prom-RDG%VdW"],["prom-RDG%st"],
                                         ["*mu"],
                                         ["tr-e*theta"],
                                         ["tr-*alpha"],
                                         ["HLgap"],
                                         ["Vol"],
                                         ["Surf"],
                                         ["Surf+","Surf-"],
                                         ["min-ESP"],
                                         ["max-ESP"],
                                         ["avg-ESP","avg-ALIE"],
                                         ["avg-ESP+"],
                                         ["avg-ESP-"],
                                         ["var-ESP"],
                                         ["var-ESP+"],
                                         ["var-ESP-"],
                                         ["*PI-ESP"],
                                         ["MPI"],
                                         ["min-LEA"],
                                         ["max-LEA"],
                                         ["avg-LEA"],
                                         ["var-LEA"],
                                         ["min-ALIE"],
                                         ["max-ALIE"],
                                         ["var-ALIE"],
                                         ["avg|EF|","0.75q|EF|","0.5q|EF|"],
                                         ["avgEF*tang","0.75qEF*tang","0.5qEF*tang"],
                                         ["avgEF*norm","0.75qEF*norm","0.5qEF*norm"],
                                         ["0.95q|EF|","0.9q|EF|"],
                                         ["0.95qEF*tang","0.9qEF*tang"],
                                         ["0.95qEF*norm","0.9qEF*norm"],
                                         ["avgEF*angle","0.75qEF*angle","0.5qEF*angle"],
                                         ["0.95qEF*angle","0.9qEF*angle"],
                                         ]          
correlated_groups["categorical_features"]=['protonated charge']

correlated_groups["atomic_features_groups"]= [["Hirshfeld","Voronoy","Lowdin","CM5","12CM5"],
                                              ["Mulliken"],
                                              ["Becke"],
                                              ["ADCH"],
                                              ["CHELPG","MK","RESP"],
                                              ["PEOE"],
                                              ["NBO-chg"],
                                              ["(a)Surf"],
                                              ["(a)Surf-","(a)Surf+"],
                                              ["(a)avg-ESP","(a)min-ESP","(a)max-ESP"],
                                              ["(a)avg-ESP+"],
                                              ["(a)avg-ESP-"],
                                              ["(a)var-ESP"],
                                              ["(a)var-ESP+"],
                                              ["(a)var-ESP-"],
                                              ["(a)*PI-ESP"],
                                              ["ESP-nucl"],
                                              ["NMR*delta"],
                                              ["(a)*mu"],
                                              ["(a)*mu-ctb"],
                                              ["(a)tr-e*theta"],
                                              ["(a)avg-ALIE","(a)max-ALIE","(a)min-ALIE","(a)avg-LEA","(a)max-LEA","(a)min-LEA"],
                                              ["(a)var-ALIE"],
                                              ["(a)var-LEA"],
                                    ]
correlated_groups["edge_groups"]=[  ["diagonal"],
                                    ["adj"],
                                    ["adj_2"],
                                    ["adj_3"],
                                    ["IBSI"],
                                    #["IBSI*relative*H"],
                                    ["Mayer-BO"],
                                    #["Mayer-BO*relative"],
                                    ["Mulliken-BO"],
                                    #["Mulliken-BO*relative"],
                                    ["FBO"],
                                    #["FBO*relative"],
                                    ["LBO"],
                                    #["LBO*relative"],
                                    ["WBO","WBO-NAO","NLMO-BO"],
                                    #["WBO*relative","WBO-NAO*relative","NLMO-BO*relative"],
                                    ["FUERZA-FC"],
                                    #["FUERZA-FC*relative"],
                                    ["BD"],
                                    #["BD*relative"],
                                    ["*mu*BP"],
                                    ["*ind*mu*BP"],
                                    ["diag-e*theta*BP"],
                                    ["diag-*theta*BP"],
                                    ["1/BD"]
                                  ]

#properties of ionizable H atom that will be projected from vector or matrix properties 
correlated_groups["alpha_masked_eq_features_groups"]= [ ["PEOE-*H"],
                                                        ["PEOE*relative*H"],
                                                        ["Mulliken-*H"],
                                                        ["Mulliken*relative*H"],
                                                        ["Hirshfeld-*H","Voronoy-*H","Lowdin-*H","CM5-*H","12CM5-*H"],
                                                        ["Hirshfeld*relative*H","Voronoy*relative*H","Lowdin*relative*H","CM5*relative*H","12CM5*relative*H"],
                                                        ["ADCH-*H"],
                                                        ["ADCH*relative*H"],
                                                        ["CHELPG-*H","MK-*H","RESP-*H"],
                                                        ["CHELPG*relative*H","MK*relative*H","RESP*relative*H"],
                                                        ["NBO-chg-*H"],
                                                        ["NBO-chg*relative*H"],
                                                        ["NMR*delta-*H"],
                                                        ["NMR*delta*relative*H"],
                                                        ["ESP-nucl-*H"],
                                                        ["ESP-nucl*relative*H"],

                                                        ["Mayer-BO-*H"],
                                                        ["Mayer-BO*relative*H"],
                                                        ["WBO-*H","WBO-NAO-*H","NLMO-BO-*H"],
                                                        ["WBO*relative*H","WBO-NAO*relative*H","NLMO-BO*relative*H"],
                                                        ["Mulliken-BO-*H"],
                                                        ["Mulliken-BO*relative*H"],
                                                        ["FBO-*H"],
                                                        ["FBO*relative*H"],
                                                        ["LBO-*H"],
                                                        ["LBO*relative*H"],
                                                        ["IBSI-*H"],
                                                        ["IBSI*relative*H"],
                                                        ["FUERZA-FC-*H"],
                                                        ["FUERZA-FC*relative*H"],
                                                        ["BD-*H"],
                                                        ["BD*relative*H"],
                                                        ["*mu*BP-*H"],
                                                        ["*ind*mu*BP-*H"],
                                                        ["diag-e*theta*BP-*H"],
                                                        ["diag-*theta*BP-*H"]                                                  
                                                      ] 
    


