#! /usr/bin/env python3.8
# -*- coding: utf-8 -*-

#dictionaries to transform the names of descriptors in this script to the names used in publication
#translating them consumes some time but also allows to change the name of the descriptors without further changes in the code
#fomat: script name is key, publication name is value

atom_features_publication_names={
        "number_of_H_difference": "number_of_H_difference",
        "chg_hirshfeld_protonated": "protonated Hirshfeld",
        "chg_hirshfeld_deprotonated": "deprotonated Hirshfeld",
        "chg_hirshfeld_difference": "Hirshfeld",
        "chg_voronoy_protonated": "protonated Voronoy",
        "chg_voronoy_deprotonated": "deprotonated Voronoy",
        "chg_voronoy_difference": "Voronoy",
        "chg_mulliken_protonated": "protonated Mulliken",
        "chg_mulliken_deprotonated": "deprotonated Mulliken",
        "chg_mulliken_difference": "Mulliken",
        "chg_lowdin_protonated": "protonated Lowdin",
        "chg_lowdin_deprotonated": "deprotonated Lowdin",
        "chg_lowdin_difference": "Lowdin",
        "chg_becke_protonated": "protonated Becke",
        "chg_becke_deprotonated": "deprotonated Becke",
        "chg_becke_difference": "Becke",
        "chg_ADCH_protonated": "protonated ADCH",
        "chg_ADCH_deprotonated": "deprotonated ADCH",
        "chg_ADCH_difference": "ADCH",
        "chg_CHELPG_protonated": "protonated CHELPG",
        "chg_CHELPG_deprotonated": "deprotonated CHELPG",
        "chg_CHELPG_difference": "CHELPG",
        "chg_MK_protonated": "protonated MK",
        "chg_MK_deprotonated": "deprotonated MK",
        "chg_MK_difference": "MK",
        "chg_CM5_protonated": "protonated CM5",
        "chg_CM5_deprotonated": "deprotonated CM5",
        "chg_CM5_difference": "CM5",
        "chg_12CM5_protonated": "protonated 12CM5",
        "chg_12CM5_deprotonated": "deprotonated 12CM5",
        "chg_12CM5_difference": "12CM5",
        "chg_RESP_protonated": "protonated RESP",
        "chg_RESP_deprotonated": "deprotonated RESP",
        "chg_RESP_difference": "RESP",
        "chg_PEOE_protonated": "protonated PEOE",
        "chg_PEOE_deprotonated": "deprotonated PEOE",
        "chg_PEOE_difference": "PEOE",
        "qams_atom_overall_surf_area_protonated": "protonated (a)Surf",
        "qams_atom_overall_surf_area_deprotonated": "deprotonated (a)Surf",
        "qams_atom_overall_surf_area_difference": "(a)Surf",
        "qams_atom_pos_surf_area_protonated": "protonated (a)Surf+",
        "qams_atom_pos_surf_area_deprotonated": "deprotonated (a)Surf+",
        "qams_atom_pos_surf_area_difference": "(a)Surf+",
        "qams_atom_neg_surf_area_protonated": "protonated (a)Surf-",
        "qams_atom_neg_surf_area_deprotonated": "deprotonated (a)Surf-",
        "qams_atom_neg_surf_area_difference": "(a)Surf-",
        "qams_atom_min_val_protonated": "protonated (a)min-ESP",
        "qams_atom_min_val_deprotonated": "deprotonated (a)min-ESP",
        "qams_atom_min_val_difference": "(a)min-ESP",
        "qams_atom_max_val_protonated": "protonated (a)max-ESP",
        "qams_atom_max_val_deprotonated": "deprotonated (a)max-ESP",
        "qams_atom_max_val_difference": "(a)max-ESP",
        "qams_atom_overall_avg_protonated": "protonated (a)avg-ESP",
        "qams_atom_overall_avg_deprotonated": "deprotonated (a)avg-ESP",
        "qams_atom_overall_avg_difference": "(a)avg-ESP",
        "qams_atom_pos_avg_protonated": "protonated (a)avg-ESP+",
        "qams_atom_pos_avg_deprotonated": "deprotonated (a)avg-ESP+",
        "qams_atom_pos_avg_difference": "(a)avg-ESP+",
        "qams_atom_neg_avg_protonated": "protonated (a)avg-ESP-",
        "qams_atom_neg_avg_deprotonated": "deprotonated (a)avg-ESP-",
        "qams_atom_neg_avg_difference": "(a)avg-ESP-",
        "qams_atom_overall_variance_protonated": "protonated (a)var-ESP",
        "qams_atom_overall_variance_deprotonated": "deprotonated (a)var-ESP",
        "qams_atom_overall_variance_difference": "(a)var-ESP",
        "qams_atom_pos_variance_protonated": "protonated (a)var-ESP+",
        "qams_atom_pos_variance_deprotonated": "deprotonated (a)var-ESP+",
        "qams_atom_pos_variance_difference": "(a)var-ESP+",
        "qams_atom_neg_variance_protonated": "protonated (a)var-ESP-",
        "qams_atom_neg_variance_deprotonated": "deprotonated (a)var-ESP-",
        "qams_atom_neg_variance_difference": "(a)var-ESP-",
        "qams_atom_Pi_protonated": "protonated (a)*PI-ESP",
        "qams_atom_Pi_deprotonated": "deprotonated (a)*PI-ESP",
        "qams_atom_Pi_difference": "(a)*PI-ESP",
        "FASA_mod_atomic_dipole_moments_protonated": "protonated (a)*mu",
        "FASA_mod_atomic_dipole_moments_deprotonated": "deprotonated (a)*mu",
        "FASA_mod_atomic_dipole_moments_difference": "(a)*mu",
        "FASA_mod_atomic_dipole_moments_contributions_protonated": "protonated (a)*mu-ctb",
        "FASA_mod_atomic_dipole_moments_contributions_deprotonated": "deprotonated (a)*mu-ctb",
        "FASA_mod_atomic_dipole_moments_contributions_difference": "(a)*mu-ctb",
        "FASA_Atomic_electronic_spatial_extent_<r^2>_protonated": "protonated (a)tr-e*theta",
        "FASA_Atomic_electronic_spatial_extent_<r^2>_deprotonated": "deprotonated (a)tr-e*theta",
        "FASA_Atomic_electronic_spatial_extent_<r^2>_difference": "(a)tr-e*theta",
        "v_at_nucleus_protonated": "protonated ESP-nucl",
        "v_at_nucleus_deprotonated": "deprotonated ESP-nucl",
        "v_at_nucleus_difference": "ESP-nucl",
        "alie_atom_overall_avg_protonated": "protonated (a)avg-ALIE",
        "alie_atom_overall_avg_deprotonated": "deprotonated (a)avg-ALIE",
        "alie_atom_overall_avg_difference": "(a)avg-ALIE",
        "alie_atom_overall_variance_protonated": "protonated (a)var-ALIE",
        "alie_atom_overall_variance_deprotonated": "deprotonated (a)var-ALIE",
        "alie_atom_overall_variance_difference": "(a)var-ALIE",
        "alie_atom_max_val_protonated": "protonated (a)max-ALIE",
        "alie_atom_max_val_deprotonated": "deprotonated (a)max-ALIE",
        "alie_atom_max_val_difference": "(a)max-ALIE",
        "alie_atom_min_val_protonated": "protonated (a)min-ALIE",
        "alie_atom_min_val_deprotonated": "deprotonated (a)min-ALIE",
        "alie_atom_min_val_difference": "(a)min-ALIE",
        "lea_atom_min_val_protonated": "protonated (a)min-LEA",
        "lea_atom_min_val_deprotonated": "deprotonated (a)min-LEA",
        "lea_atom_min_val_difference": "(a)min-LEA",
        "lea_atom_max_val_protonated": "protonated (a)max-LEA",
        "lea_atom_max_val_deprotonated": "deprotonated (a)max-LEA",
        "lea_atom_max_val_difference": "(a)max-LEA",
        "lea_atom_overall_avg_protonated": "protonated (a)avg-LEA",
        "lea_atom_overall_avg_deprotonated": "deprotonated (a)avg-LEA",
        "lea_atom_overall_avg_difference": "(a)avg-LEA",
        "lea_atom_neg_variance_protonated": "protonated (a)var-LEA",
        "lea_atom_neg_variance_deprotonated": "deprotonated (a)var-LEA",
        "lea_atom_neg_variance_difference": "(a)var-LEA",
        "nbo_charges_protonated": "protonated NBO-chg",
        "nbo_charges_deprotonated": "deprotonated NBO-chg",
        "nbo_charges_difference": "NBO-chg",
        "chemical_isotropic_shield_protonated": "protonated NMR*delta",
        "chemical_isotropic_shield_deprotonated": "deprotonated NMR*delta",
        "chemical_isotropic_shield_difference": "NMR*delta",
        "chg_hirshfeld_H_protonated": "protonated Hirshfeld-*H",
        "chg_hirshfeld_H_deprotonated": "deprotonated Hirshfeld-*H",
        "chg_hirshfeld_H_difference": "Hirshfeld-*H",
        "chg_voronoy_H_protonated": "protonated Voronoy-*H",
        "chg_voronoy_H_deprotonated": "deprotonated Voronoy-*H",
        "chg_voronoy_H_difference": "Voronoy-*H",
        "chg_mulliken_H_protonated": "protonated Mulliken-*H",
        "chg_mulliken_H_deprotonated": "deprotonated Mulliken-*H",
        "chg_mulliken_H_difference": "Mulliken-*H",
        "chg_lowdin_H_protonated": "protonated Lowdin-*H",
        "chg_lowdin_H_deprotonated": "deprotonated Lowdin-*H",
        "chg_lowdin_H_difference": "Lowdin-*H",
        "chg_becke_H_protonated": "protonated Becke-*H",
        "chg_becke_H_deprotonated": "deprotonated Becke-*H",
        "chg_becke_H_difference": "Becke-*H",
        "chg_ADCH_H_protonated": "protonated ADCH-*H",
        "chg_ADCH_H_deprotonated": "deprotonated ADCH-*H",
        "chg_ADCH_H_difference": "ADCH-*H",
        "chg_CHELPG_H_protonated": "protonated CHELPG-*H",
        "chg_CHELPG_H_deprotonated": "deprotonated CHELPG-*H",
        "chg_CHELPG_H_difference": "CHELPG-*H",
        "chg_MK_H_protonated": "protonated MK-*H",
        "chg_MK_H_deprotonated": "deprotonated MK-*H",
        "chg_MK_H_difference": "MK-*H",
        "chg_CM5_H_protonated": "protonated CM5-*H",
        "chg_CM5_H_deprotonated": "deprotonated CM5-*H",
        "chg_CM5_H_difference": "CM5-*H",
        "chg_12CM5_H_protonated": "protonated 12CM5-*H",
        "chg_12CM5_H_deprotonated": "deprotonated 12CM5-*H",
        "chg_12CM5_H_difference": "12CM5-*H",
        "chg_RESP_H_protonated": "protonated RESP-*H",
        "chg_RESP_H_deprotonated": "deprotonated RESP-*H",
        "chg_RESP_H_difference": "RESP-*H",
        "chg_PEOE_H_protonated": "protonated PEOE-*H",
        "chg_PEOE_H_deprotonated": "deprotonated PEOE-*H",
        "chg_PEOE_H_difference": "PEOE-*H",
        "qams_atom_overall_surf_area_H_protonated": "protonated (a)Surf-*H",
        "qams_atom_overall_surf_area_H_deprotonated": "deprotonated (a)Surf-*H",
        "qams_atom_overall_surf_area_H_difference": "(a)Surf-*H",
        "qams_atom_pos_surf_area_H_protonated": "protonated (a)Surf-*H+",
        "qams_atom_pos_surf_area_H_deprotonated": "deprotonated (a)Surf-*H+",
        "qams_atom_pos_surf_area_H_difference": "(a)Surf-*H+",
        "qams_atom_neg_surf_area_H_protonated": "protonated (a)Surf-*H-",
        "qams_atom_neg_surf_area_H_deprotonated": "deprotonated (a)Surf-*H-",
        "qams_atom_neg_surf_area_H_difference": "(a)Surf-*H-",
        "qams_atom_min_val_H_protonated": "protonated (a)min-ESP-*H",
        "qams_atom_min_val_H_deprotonated": "deprotonated (a)min-ESP-*H",
        "qams_atom_min_val_H_difference": "(a)min-ESP-*H",
        "qams_atom_max_val_H_protonated": "protonated (a)max-ESP-*H",
        "qams_atom_max_val_H_deprotonated": "deprotonated (a)max-ESP-*H",
        "qams_atom_max_val_H_difference": "(a)max-ESP-*H",
        "qams_atom_overall_avg_H_protonated": "protonated (a)avg-ESP-*H",
        "qams_atom_overall_avg_H_deprotonated": "deprotonated (a)avg-ESP-*H",
        "qams_atom_overall_avg_H_difference": "(a)avg-ESP-*H",
        "qams_atom_pos_avg_H_protonated": "protonated (a)avg-ESP-*H+",
        "qams_atom_pos_avg_H_deprotonated": "deprotonated (a)avg-ESP-*H+",
        "qams_atom_pos_avg_H_difference": "(a)avg-ESP-*H+",
        "qams_atom_neg_avg_H_protonated": "protonated (a)avg-ESP-*H-",
        "qams_atom_neg_avg_H_deprotonated": "deprotonated (a)avg-ESP-*H-",
        "qams_atom_neg_avg_H_difference": "(a)avg-ESP-*H-",
        "qams_atom_overall_variance_H_protonated": "protonated (a)var-ESP-*H",
        "qams_atom_overall_variance_H_deprotonated": "deprotonated (a)var-ESP-*H",
        "qams_atom_overall_variance_H_difference": "(a)var-ESP-*H",
        "qams_atom_pos_variance_H_protonated": "protonated (a)var-ESP-*H+",
        "qams_atom_pos_variance_H_deprotonated": "deprotonated (a)var-ESP-*H+",
        "qams_atom_pos_variance_H_difference": "(a)var-ESP-*H+",
        "qams_atom_neg_variance_H_protonated": "protonated (a)var-ESP-*H-",
        "qams_atom_neg_variance_H_deprotonated": "deprotonated (a)var-ESP-*H-",
        "qams_atom_neg_variance_H_difference": "(a)var-ESP-*H-",
        "qams_atom_Pi_H_protonated": "protonated (a)*PI-ESP-*H",
        "qams_atom_Pi_H_deprotonated": "deprotonated (a)*PI-ESP-*H",
        "qams_atom_Pi_H_difference": "(a)*PI-ESP-*H",
        "FASA_mod_atomic_dipole_moments_H_protonated": "protonated (a)*mu-*H",
        "FASA_mod_atomic_dipole_moments_H_deprotonated": "deprotonated (a)*mu-*H",
        "FASA_mod_atomic_dipole_moments_H_difference": "(a)*mu-*H",
        "FASA_mod_atomic_dipole_moments_contributions_H_protonated": "protonated (a)*mu-ctb-*H",
        "FASA_mod_atomic_dipole_moments_contributions_H_deprotonated": "deprotonated (a)*mu-ctb-*H",
        "FASA_mod_atomic_dipole_moments_contributions_H_difference": "(a)*mu-ctb-*H",
        "FASA_Atomic_electronic_spatial_extent_<r^2>_H_protonated": "protonated (a)tr-e*theta-*H",
        "FASA_Atomic_electronic_spatial_extent_<r^2>_H_deprotonated": "deprotonated (a)tr-e*theta-*H",
        "FASA_Atomic_electronic_spatial_extent_<r^2>_H_difference": "(a)tr-e*theta-*H",
        "v_at_nucleus_H_protonated": "protonated ESP-nucl-*H",
        "v_at_nucleus_H_deprotonated": "deprotonated ESP-nucl-*H",
        "v_at_nucleus_H_difference": "ESP-nucl-*H",
        "alie_atom_overall_avg_H_protonated": "protonated (a)avg-ALIE-*H",
        "alie_atom_overall_avg_H_deprotonated": "deprotonated (a)avg-ALIE-*H",
        "alie_atom_overall_avg_H_difference": "(a)avg-ALIE-*H",
        "alie_atom_overall_variance_H_protonated": "protonated (a)var-ALIE-*H",
        "alie_atom_overall_variance_H_deprotonated": "deprotonated (a)var-ALIE-*H",
        "alie_atom_overall_variance_H_difference": "(a)var-ALIE-*H",
        "alie_atom_max_val_H_protonated": "protonated (a)max-ALIE-*H",
        "alie_atom_max_val_H_deprotonated": "deprotonated (a)max-ALIE-*H",
        "alie_atom_max_val_H_difference": "(a)max-ALIE-*H",
        "alie_atom_min_val_H_protonated": "protonated (a)min-ALIE-*H",
        "alie_atom_min_val_H_deprotonated": "deprotonated (a)min-ALIE-*H",
        "alie_atom_min_val_H_difference": "(a)min-ALIE-*H",
        "lea_atom_min_val_H_protonated": "protonated (a)min-LEA-*H",
        "lea_atom_min_val_H_deprotonated": "deprotonated (a)min-LEA-*H",
        "lea_atom_min_val_H_difference": "(a)min-LEA-*H",
        "lea_atom_max_val_H_protonated": "protonated (a)max-LEA-*H",
        "lea_atom_max_val_H_deprotonated": "deprotonated (a)max-LEA-*H",
        "lea_atom_max_val_H_difference": "(a)max-LEA-*H",
        "lea_atom_overall_avg_H_protonated": "protonated (a)avg-LEA-*H",
        "lea_atom_overall_avg_H_deprotonated": "deprotonated (a)avg-LEA-*H",
        "lea_atom_overall_avg_H_difference": "(a)avg-LEA-*H",
        "lea_atom_pos_avg_H_protonated": "protonated (a)var-LEA-*H",
        "lea_atom_pos_variance_H_difference": "deprotonated (a)var-LEA-*H",
        "lea_atom_neg_variance_H_deprotonated": "(a)var-LEA-*H",
        "nbo_charges_H_protonated": "protonated NBO-chg-*H",
        "nbo_charges_H_deprotonated": "deprotonated NBO-chg-*H",
        "nbo_charges_H_difference": "NBO-chg-*H",
        "chemical_isotropic_shield_H_protonated": "protonated NMR*delta-*H",
        "chemical_isotropic_shield_H_deprotonated": "deprotonated NMR*delta-*H",
        "chemical_isotropic_shield_H_difference": "NMR*delta-*H",
        "rel_chemical_isotropic_shield_H_protonated": "protonated NMR*delta*relative*H",
        "rel_chemical_isotropic_shield_H_deprotonated": "deprotonated NMR*delta*relative*H",
        "rel_chemical_isotropic_shield_H_difference": "NMR*delta*relative*H",
        "rel_chg_hirshfeld_H_protonated": "protonated Hirshfeld*relative*H",
        "rel_chg_hirshfeld_H_deprotonated": "deprotonated Hirshfeld*relative*H",
        "rel_chg_hirshfeld_H_difference": "Hirshfeld*relative*H",
        "rel_chg_voronoy_H_protonated": "protonated Voronoy*relative*H",
        "rel_chg_voronoy_H_deprotonated": "deprotonated Voronoy*relative*H",
        "rel_chg_voronoy_H_difference": "Voronoy*relative*H",
        "rel_chg_mulliken_H_protonated": "protonated Mulliken*relative*H",
        "rel_chg_mulliken_H_deprotonated": "deprotonated Mulliken*relative*H",
        "rel_chg_mulliken_H_difference": "Mulliken*relative*H",
        "rel_chg_lowdin_H_protonated": "protonated Lowdin*relative*H",
        "rel_chg_lowdin_H_deprotonated": "deprotonated Lowdin*relative*H",
        "rel_chg_lowdin_H_difference": "Lowdin*relative*H",
        "rel_chg_becke_H_protonated": "protonated Becke*relative*H",
        "rel_chg_becke_H_deprotonated": "deprotonated Becke*relative*H",
        "rel_chg_becke_H_difference": "Becke*relative*H",
        "rel_chg_ADCH_H_protonated": "protonated ADCH*relative*H",
        "rel_chg_ADCH_H_deprotonated": "deprotonated ADCH*relative*H",
        "rel_chg_ADCH_H_difference": "ADCH*relative*H",
        "rel_chg_CHELPG_H_protonated": "protonated CHELPG*relative*H",
        "rel_chg_CHELPG_H_deprotonated": "deprotonated CHELPG*relative*H",
        "rel_chg_CHELPG_H_difference": "CHELPG*relative*H",
        "rel_chg_MK_H_protonated": "protonated MK*relative*H",
        "rel_chg_MK_H_deprotonated": "deprotonated MK*relative*H",
        "rel_chg_MK_H_difference": "MK*relative*H",
        "rel_chg_CM5_H_protonated": "protonated CM5*relative*H",
        "rel_chg_CM5_H_deprotonated": "deprotonated CM5*relative*H",
        "rel_chg_CM5_H_difference": "CM5*relative*H",
        "rel_chg_12CM5_H_protonated": "protonated 12CM5*relative*H",
        "rel_chg_12CM5_H_deprotonated": "deprotonated 12CM5*relative*H",
        "rel_chg_12CM5_H_difference": "12CM5*relative*H",
        "rel_chg_RESP_H_protonated": "protonated RESP*relative*H",
        "rel_chg_RESP_H_deprotonated": "deprotonated RESP*relative*H",
        "rel_chg_RESP_H_difference": "RESP*relative*H",
        "rel_chg_PEOE_H_protonated": "protonated PEOE*relative*H",
        "rel_chg_PEOE_H_deprotonated": "deprotonated PEOE*relative*H",
        "rel_chg_PEOE_H_difference": "PEOE*relative*H",
        "rel_v_at_nucleus_H_protonated": "protonated ESP-nucl*relative*H",
        "rel_v_at_nucleus_H_deprotonated": "deprotonated ESP-nucl*relative*H",
        "rel_v_at_nucleus_H_difference": "ESP-nucl*relative*H",
        "rel_nbo_charges_H_protonated": "protonated NBO-chg*relative*H",
        "rel_nbo_charges_H_deprotonated": "deprotonated NBO-chg*relative*H",
        "rel_nbo_charges_H_difference": "NBO-chg*relative*H",
    }

vector_features_publication_names={
        "bo_mayer_protonated": "protonated Mayer-BO",
        "bo_mayer_deprotonated": "deprotonated Mayer-BO",
        "bo_mayer_difference": "Mayer-BO",
        "bo_wiberg_protonated": "protonated WBO",
        "bo_wiberg_deprotonated": "deprotonated WBO",
        "bo_wiberg_difference": "WBO",
        "bo_mulliken_protonated": "protonated Mulliken-BO",
        "bo_mulliken_deprotonated": "deprotonated Mulliken-BO",
        "bo_mulliken_difference": "Mulliken-BO",
        "bo_fuzzy_protonated": "protonated FBO",
        "bo_fuzzy_deprotonated": "deprotonated FBO",
        "bo_fuzzy_difference": "FBO",
        "bo_laplacian_protonated": "protonated LBO",
        "bo_laplacian_deprotonated": "deprotonated LBO",
        "bo_laplacian_difference": "LBO",
        "bo_IBSI_protonated": "protonated IBSI",
        "bo_IBSI_deprotonated": "deprotonated IBSI",
        "bo_IBSI_difference": "IBSI",
        "force_constants_protonated": "protonated FUERZA-FC",
        "force_constants_deprotonated": "deprotonated FUERZA-FC",
        "force_constants_difference": "FUERZA-FC",
        "inv_distances_protonated": "protonated 1/BD",
        "inv_distances_deprotonated": "deprotonated 1/BD",
        "inv_distances_difference": "1/BD",
        "bond_distances_protonated": "protonated BD",
        "bond_distances_deprotonated": "deprotonated BD",
        "bond_distances_difference": "BD",
        "nbo_nbi_bond_orders_protonated": "protonated NBI",
        "nbo_nbi_bond_orders_deprotonated": "deprotonated NBI",
        "nbo_nbi_bond_orders_difference": "NBI",
        "rel_nbo_nbi_bond_orders_protonated": "protonated NBI*relative",
        "rel_nbo_nbi_bond_orders_deprotonated": "deprotonated NBI*relative",
        "rel_nbo_nbi_bond_orders_difference": "NBI*relative",
        "nbo_wiberg_bond_orders_protonated": "protonated WBO-NAO",
        "nbo_wiberg_bond_orders_deprotonated": "deprotonated WBO-NAO",
        "nbo_wiberg_bond_orders_difference": "WBO-NAO",
        "rel_nbo_wiberg_bond_orders_protonated": "protonated WBO-NAO*relative",
        "rel_nbo_wiberg_bond_orders_deprotonated": "deprotonated WBO-NAO*relative",
        "rel_nbo_wiberg_bond_orders_difference": "WBO-NAO*relative",
        "nbo_nlmonpa_bond_orders_protonated": "protonated NLMO-BO",
        "nbo_nlmonpa_bond_orders_deprotonated": "deprotonated NLMO-BO",
        "nbo_nlmonpa_bond_orders_difference": "NLMO-BO",
        "rel_nbo_nlmonpa_bond_orders_protonated": "protonated NLMO-BO*relative",
        "rel_nbo_nlmonpa_bond_orders_deprotonated": "deprotonated NLMO-BO*relative",
        "rel_nbo_nlmonpa_bond_orders_difference": "NLMO-BO*relative",
        "molecular_dipole_projected_on_bonds_protonated": "protonated *mu*BP",
        "molecular_dipole_projected_on_bonds_deprotonated": "deprotonated *mu*BP",
        "molecular_dipole_projected_on_bonds_difference": "*mu*BP",
        "polarizability_wr2_bonds_projected_on_bonds_protonated": "protonated *ind*mu*BP",
        "polarizability_wr2_bonds_projected_on_bonds_deprotonated": "deprotonated *ind*mu*BP",
        "polarizability_wr2_bonds_projected_on_bonds_difference": "*ind*mu*BP",
        "polarizability_wr2_bonds_with_H_projected_on_bonds_protonated": "protonated *ind-*H*mu*BP",
        "polarizability_wr2_bonds_with_H_projected_on_bonds_deprotonated": "deprotonated *ind-*H*mu*BP",
        "polarizability_wr2_bonds_with_H_projected_on_bonds_difference": "*ind-*H*mu*BP",
        "e_spatial_extent_projected_on_bonds_protonated": "protonated diag-e*theta*BP",
        "e_spatial_extent_projected_on_bonds_deprotonated": "deprotonated diag-e*theta*BP",
        "e_spatial_extent_projected_on_bonds_difference": "diag-e*theta*BP",
        "tot_spatial_extent_projected_on_bonds_protonated": "protonated diag-*theta*BP",
        "tot_spatial_extent_projected_on_bonds_deprotonated": "deprotonated diag-*theta*BP",
        "tot_spatial_extent_projected_on_bonds_difference": "diag-*theta*BP",
        "bo_mayer_H_protonated": "protonated Mayer-BO-*H",
        "bo_mayer_H_deprotonated": "deprotonated Mayer-BO-*H",
        "bo_mayer_H_difference": "Mayer-BO-*H",
        "bo_wiberg_H_protonated": "protonated WBO-*H",
        "bo_wiberg_H_deprotonated": "deprotonated WBO-*H",
        "bo_wiberg_H_difference": "WBO-*H",
        "bo_mulliken_H_protonated": "protonated Mulliken-BO-*H",
        "bo_mulliken_H_deprotonated": "deprotonated Mulliken-BO-*H",
        "bo_mulliken_H_difference": "Mulliken-BO-*H",
        "bo_fuzzy_H_protonated": "protonated FBO-*H",
        "bo_fuzzy_H_deprotonated": "deprotonated FBO-*H",
        "bo_fuzzy_H_difference": "FBO-*H",
        "bo_laplacian_H_protonated": "protonated LBO-*H",
        "bo_laplacian_H_deprotonated": "deprotonated LBO-*H",
        "bo_laplacian_H_difference": "LBO-*H",
        "bo_IBSI_H_protonated": "protonated IBSI-*H",
        "bo_IBSI_H_deprotonated": "deprotonated IBSI-*H",
        "bo_IBSI_H_difference": "IBSI-*H",
        "force_constants_H_protonated": "protonated FUERZA-FC-*H",
        "force_constants_H_deprotonated": "deprotonated FUERZA-FC-*H",
        "force_constants_H_difference": "FUERZA-FC-*H",
        "rel_force_constants_H_protonated": "protonated FUERZA-FC*relative*H",
        "rel_force_constants_H_deprotonated": "deprotonated FUERZA-FC*relative*H",
        "rel_force_constants_H_difference": "FUERZA-FC*relative*H",
        "inv_distances_H_protonated": "protonated 1/BD-*H",
        "inv_distances_H_deprotonated": "deprotonated 1/BD-*H",
        "inv_distances_H_difference": "1/BD-*H",
        "bond_distances_H_protonated": "protonated BD-*H",
        "bond_distances_H_deprotonated": "deprotonated BD-*H",
        "bond_distances_H_difference": "BD-*H",
        "rel_bond_distances_H_protonated": "protonated BD*relative*H",
        "rel_bond_distances_H_deprotonated": "deprotonated BD*relative*H",
        "rel_bond_distances_H_difference": "BD*relative*H",
        "nbo_nbi_bond_orders_H_protonated": "protonated NBI-*H",
        "nbo_nbi_bond_orders_H_deprotonated": "deprotonated NBI-*H",
        "nbo_nbi_bond_orders_H_difference": "NBI-*H",
        "rel_nbo_nbi_bond_orders_H_protonated": "protonated NBI*relative*H",
        "rel_nbo_nbi_bond_orders_H_deprotonated": "deprotonated NBI*relative*H",
        "rel_nbo_nbi_bond_orders_H_difference": "NBI*relative*H",
        "nbo_wiberg_bond_orders_H_protonated": "protonated WBO-NAO-*H",
        "nbo_wiberg_bond_orders_H_deprotonated": "deprotonated WBO-NAO-*H",
        "nbo_wiberg_bond_orders_H_difference": "WBO-NAO-*H",
        "rel_nbo_wiberg_bond_orders_H_protonated": "protonated WBO-NAO*relative*H",
        "rel_nbo_wiberg_bond_orders_H_deprotonated": "deprotonated WBO-NAO*relative*H",
        "rel_nbo_wiberg_bond_orders_H_difference": "WBO-NAO*relative*H",
        "nbo_nlmonpa_bond_orders_H_protonated": "protonated NLMO-BO-*H",
        "nbo_nlmonpa_bond_orders_H_deprotonated": "deprotonated NLMO-BO-*H",
        "nbo_nlmonpa_bond_orders_H_difference": "NLMO-BO-*H",
        "rel_nbo_nlmonpa_bond_orders_H_protonated": "protonated NLMO-BO*relative*H",
        "rel_nbo_nlmonpa_bond_orders_H_deprotonated": "deprotonated NLMO-BO*relative*H",
        "rel_nbo_nlmonpa_bond_orders_H_difference": "NLMO-BO*relative*H",
        "rel_bo_mayer_H_protonated": "protonated Mayer-BO*relative*H",
        "rel_bo_mayer_H_deprotonated": "deprotonated Mayer*relativeBO-*H",
        "rel_bo_mayer_H_difference": "Mayer-BO*relative*H",
        "rel_bo_wiberg_H_protonated": "protonated WBO*relative*H",
        "rel_bo_wiberg_H_deprotonated": "deprotonated WBO*relative*H",
        "rel_bo_wiberg_H_difference": "WBO*relative*H",
        "rel_bo_mulliken_H_protonated": "protonated Mulliken-BO*relative*H",
        "rel_bo_mulliken_H_deprotonated": "deprotonated Mulliken-BO*relative*H",
        "rel_bo_mulliken_H_difference": "Mulliken-BO*relative*H",
        "rel_bo_fuzzy_H_protonated": "protonated FBO*relative*H",
        "rel_bo_fuzzy_H_deprotonated": "deprotonated FBO*relative*H",
        "rel_bo_fuzzy_H_difference": "FBO*relative*H",
        "rel_bo_laplacian_H_protonated": "protonated LBO*relative*H",
        "rel_bo_laplacian_H_deprotonated": "deprotonated LBO*relative*H",
        "rel_bo_laplacian_H_difference": "LBO*relative*H",
        "rel_bo_IBSI_H_protonated": "protonated IBSI*relative*H",
        "rel_bo_IBSI_H_deprotonated": "deprotonated IBSI*relative*H",
        "rel_bo_IBSI_H_difference": "IBSI*relative*H",
        "molecular_dipole_projected_on_bonds_H_protonated": "protonated *mu*BP-*H",
        "molecular_dipole_projected_on_bonds_H_deprotonated": "deprotonated *mu*BP-*H",
        "molecular_dipole_projected_on_bonds_H_difference": "*mu*BP-*H",
        "polarizability_wr2_bonds_projected_on_bonds_H_protonated": "protonated *ind*mu*BP-*H",
        "polarizability_wr2_bonds_projected_on_bonds_H_deprotonated": "deprotonated *ind*mu*BP-*H",
        "polarizability_wr2_bonds_projected_on_bonds_H_difference": "*ind*mu*BP-*H",
        "e_spatial_extent_projected_on_bonds_H_protonated": "protonated diag-e*theta*BP-*H",
        "e_spatial_extent_projected_on_bonds_H_deprotonated": "deprotonated diag-e*theta*BP-*H",
        "e_spatial_extent_projected_on_bonds_H_difference": "diag-e*theta*BP-*H",
        "tot_spatial_extent_projected_on_bonds_H_protonated": "protonated diag-*theta*BP-*H",
        "tot_spatial_extent_projected_on_bonds_H_deprotonated": "deprotonated diag-*theta*BP-*H",
        "tot_spatial_extent_projected_on_bonds_H_difference": "diag-*theta*BP-*H",
    }


#fomat: pubilcation name is key, script name is value
inv_atom_features_publication_names={v: k for k, v in atom_features_publication_names.items()}
inv_vector_features_publication_names={v: k for k, v in vector_features_publication_names.items()}



#method for translating text in feature names to unicode symbols. 

def transl_symbols(text):
    text=str(text)
    replace_chars={   #order is important!!!
        #bond orders:
        "BO*relative*H":"BO\u2797(XH)",
        "BD*relative*H":"BD\u2797(XH)",
        "NBI*relative-*H":"NBI\u2797(XH)",
        "WBO-NAO*relative*H":"WBO-NAO\u2797(XH)",
        "IBSI*relative*H":"IBSI\u2797(XH)",
        "FUERZA-FC*relative*H":"FUERZA-FC\u2797(XH)",
        "NBI*relative*H":"NBI\u2797(XH)",
        "BO-*H":"BO-(XH)",
        "BD-*H":"BD-(XH)",
        "NBI-*H":"NBI-(XH)",
        "WBO-NAO-*H":"WBO-NAO-(XH)",
        "IBSI-*H":"IBSI-(XH)",
        "FUERZA-FC-*H":"FUERZA-FC-(XH)",

        #properties projected on bonds:
        "*BP-*H":"\u2926(XH)",
        
        #atomic charges
        "*relative*H_alpha": "\u00f7(H\u03b1)",#"\u2a38(H\u03b1)",
        "*relative*H_beta": "\u00f7(H\u03b1)",#"\u2a38(H\u03b2)",
        "*relative*H_gamma": "\u00f7(H\u03b1)",#"\u2a38(H\u03b3)",
        "-*H_alpha":"(H\u03b1)",
        "-*H_beta":"(H\u03b2)",
        "-*H_gamma":"(H\u03b3)",
        "-*H+_alpha":"\u2295(H\u03b1)",
        "-*H+_beta":"\u2295(H\u03b2)",
        "-*H+_gamma":"\u2295(H\u03b3)",
        "-*H-_alpha":"\u2296(H\u03b1)",
        "-*H-_beta":"\u2296(H\u03b2)",
        "-*H-_gamma":"\u2296(H\u03b3)",
        
        "+_alpha":"\u2295(\u03b1)",
        "-_alpha":"\u2296(\u03b1)",
        "+_beta":"\u2295(\u03b2)",
        "-_beta":"\u2296(\u03b2)",
        "+_gamma":"\u2295(\u03b3)",
        "-_gamma":"\u2296(\u03b3)",
        "_alpha":"(\u03b1)",
        "_beta":"(\u03b2)",
        "_gamma":"(\u03b3)",
        
        #molecular properties  
        "Surf+":"Surf\u2295",
        "Surf-":"Surf\u2296",
        "SMDsurf+":"SMDSurf\u2295",
        "SMDsurf-":"SMDSurf\u2296",
        "SMDsurf":"SMDSurf",
        "ESP+":"ESP\u2295",
        "ESP-":"ESP\u2296",   
        "*mu":"\u03bc",
        "*theta":"\u03b8",
        "*alpha":"\u03b1",
        "*PI":"\u03a0",
        #"*angle":"\u29A1",
        "*angle":"\u15ce",
        "*norm":"\u27c2",
        "*tang":"\u2225",
        "*BP":"\u2926",
        "*ind":"'",
        "*H":"\u24bD",
        "(a)":"\u249C",
        "*delta":"\u03b4",
        "*relative":"\u2797",
        "deprotonated ":"(B)",
        "protonated ":"(AH)",
    }
        
    for c,u in replace_chars.items(): 
        if c in text: text=text.replace(c,u)
    
    return text
  


