#! /usr/bin/env python3
# -*- coding: utf-8 -*-

repeated_molecules={}

repeated_molecules["4hydroxypyridine-neut*"]=2
repeated_molecules["4hydroxypyridine-cation*"]=2
repeated_molecules["4mercaptopyridine-cation*"]=2
repeated_molecules["4mercaptopyridine-neut2"]=2
repeated_molecules["11cyclopentanediacetic-an*"]=2
repeated_molecules["36dichlorophtalic-an*"]= 2
repeated_molecules["dichlorosuccinic-an*"]=   2
repeated_molecules["dihydroxymandelic-an*"]=       2
repeated_molecules["mesodichlorosuccinic-an*"]=    2
repeated_molecules["23dimethoxyquinoxaline-cation*"]= 2
repeated_molecules["benzenehexacarboxylic-an*"]=   6
repeated_molecules["benzenehexacarboxylic-2an*"]=  6
repeated_molecules["benzenehexacarboxylic-4an*"]=  6
repeated_molecules["benzenehexacarboxylic-5an*"]=  6
repeated_molecules["benzenepentacarboxylic-an1"]=2;repeated_molecules["benzenepentacarboxylic-an2"]=2;repeated_molecules["benzenepentacarboxylic-an3"]=2
repeated_molecules["benzenepentacarboxylic-an4"]=2;repeated_molecules["benzenepentacarboxylic-an5"]=2;repeated_molecules["benzenepentacarboxylic-an6"]=2
repeated_molecules["benzenepentacarboxylic-an6"]=2;repeated_molecules["benzenepentacarboxylic-an7"]=2;repeated_molecules["benzenepentacarboxylic-an8"]=2
repeated_molecules["benzenepentacarboxylic-an9"]=2;repeated_molecules["benzenepentacarboxylic-an10"]=2;repeated_molecules["benzenepentacarboxylic-an11"]=2
repeated_molecules["benzenepentacarboxylic-an12"]=2;repeated_molecules["benzenepentacarboxylic-an13"]=2;repeated_molecules["benzenepentacarboxylic-an14"]=2
repeated_molecules["benzenepentacarboxylic-an15"]=2;repeated_molecules["benzenepentacarboxylic-an16"]=2;repeated_molecules["benzenepentacarboxylic-an17"]=2
repeated_molecules["benzenepentacarboxylic-an18"]=2;repeated_molecules["benzenepentacarboxylic-an19"]=2;repeated_molecules["benzenepentacarboxylic-an20"]=2
repeated_molecules["benzenepentacarboxylic-an21"]=2;repeated_molecules["benzenepentacarboxylic-an22"]=2;repeated_molecules["benzenepentacarboxylic-an23"]=2
repeated_molecules["benzenepentacarboxylic-an24"]=2;repeated_molecules["benzenepentacarboxylic-an25"]=2;repeated_molecules["benzenepentacarboxylic-an26"]=2
repeated_molecules["benzenepentacarboxylic-an101"]=2;repeated_molecules["benzenepentacarboxylic-an102"]=2;repeated_molecules["benzenepentacarboxylic-an103"]=2
repeated_molecules["benzenepentacarboxylic-an104"]=2;repeated_molecules["benzenepentacarboxylic-an105"]=2;repeated_molecules["benzenepentacarboxylic-an106"]=2
repeated_molecules["benzenepentacarboxylic-an107"]=2;repeated_molecules["benzenepentacarboxylic-an108"]=2;repeated_molecules["benzenepentacarboxylic-an109"]=2
repeated_molecules["benzenepentacarboxylic-4an1"]=2; repeated_molecules["benzenepentacarboxylic-4an2"]=2
repeated_molecules["1245benzenetetracarboxylic-3an*"]= 4
repeated_molecules["1245benzenetetracarboxylic-an1*"]=  4
repeated_molecules["1234benzenetetracarboxylic-3an*"]=  2
repeated_molecules["1234benzenetetracarboxylic-an*"]=   2
repeated_molecules["1235benzenetetracarboxylic-3an2*"]=   2  
repeated_molecules["1235benzenetetracarboxylic-an1"]=2;repeated_molecules["1235benzenetetracarboxylic-an2"]=2;repeated_molecules["1235benzenetetracarboxylic-an3"]=2;
repeated_molecules["1235benzenetetracarboxylic-an4"]=2;repeated_molecules["1235benzenetetracarboxylic-an5"]=2;repeated_molecules["1235benzenetetracarboxylic-an6"]=2;
repeated_molecules["1235benzenetetracarboxylic-an7"]=2;repeated_molecules["1235benzenetetracarboxylic-an8"]=2;repeated_molecules["1235benzenetetracarboxylic-an9"]=2;
repeated_molecules["1235benzenetetracarboxylic-an10"]=2;repeated_molecules["1235benzenetetracarboxylic-an11"]=2;repeated_molecules["1235benzenetetracarboxylic-an12"]=2;
repeated_molecules["1235benzenetetracarboxylic-an13"]=2
repeated_molecules["123benzenetricarboxylic-2an1"]=2;repeated_molecules["123benzenetricarboxylic-2an5"]=2; repeated_molecules["123benzenetricarboxylic-2an6"]=2
repeated_molecules["123benzenetricarboxylic-an1"]=2;repeated_molecules["123benzenetricarboxylic-an5"]=2;repeated_molecules["123benzenetricarboxylic-an6"]=2
repeated_molecules["123benzenetricarboxylic-an105"]=2;
repeated_molecules["methylmalonic-an*"]=2
repeated_molecules["propanetricarboxylic-an1"]=2;repeated_molecules["propanetricarboxylic-an2"]=2; repeated_molecules["propanetricarboxylic-an3"]=2;repeated_molecules["propanetricarboxylic-an4"]=2;repeated_molecules["propanetricarboxylic-an5"]=2
repeated_molecules["propanetricarboxylic-an6"]=2;repeated_molecules["propanetricarboxylic-an7"]=2; repeated_molecules["propanetricarboxylic-an8"]=2;repeated_molecules["propanetricarboxylic-an9"]=2;repeated_molecules["propanetricarboxylic-an10"]=2
repeated_molecules["propanetricarboxylic-an11"]=2;repeated_molecules["propanetricarboxylic-an12"]=2; repeated_molecules["propanetricarboxylic-an13"]=2;repeated_molecules["propanetricarboxylic-an14"]=2;repeated_molecules["propanetricarboxylic-an15"]=2
repeated_molecules["propanetricarboxylic-an16"]=2;repeated_molecules["propanetricarboxylic-an17"]=2; repeated_molecules["propanetricarboxylic-an18"]=2;repeated_molecules["propanetricarboxylic-an19"]=2;repeated_molecules["propanetricarboxylic-an20"]=2
repeated_molecules["propanetricarboxylic-an21"]=2;repeated_molecules["propanetricarboxylic-an22"]=2; repeated_molecules["propanetricarboxylic-an23"]=2;repeated_molecules["propanetricarboxylic-an24"]=2;repeated_molecules["propanetricarboxylic-an25"]=2
repeated_molecules["propanetricarboxylic-an26"]=2;repeated_molecules["propanetricarboxylic-an27"]=2; repeated_molecules["propanetricarboxylic-an28"]=2;repeated_molecules["propanetricarboxylic-an29"]=2;repeated_molecules["propanetricarboxylic-an30"]=2
repeated_molecules["propanetricarboxylic-an11"]=2;repeated_molecules["propanetricarboxylic-an32"]=2; repeated_molecules["propanetricarboxylic-an33"]=2;repeated_molecules["propanetricarboxylic-an34"]=2;repeated_molecules["propanetricarboxylic-an35"]=2
repeated_molecules["propanetricarboxylic-an16"]=2;repeated_molecules["propanetricarboxylic-an37"]=2; repeated_molecules["propanetricarboxylic-an38"]=2;repeated_molecules["propanetricarboxylic-an39"]=2;repeated_molecules["propanetricarboxylic-an40"]=2
repeated_molecules["propanetricarboxylic-an11"]=2;repeated_molecules["propanetricarboxylic-an42"]=2; repeated_molecules["propanetricarboxylic-an43"]=2;repeated_molecules["propanetricarboxylic-an44"]=2;repeated_molecules["propanetricarboxylic-an45"]=2
repeated_molecules["propanetricarboxylic-an16"]=2;repeated_molecules["propanetricarboxylic-an47"]=2; repeated_molecules["propanetricarboxylic-an48"]=2;repeated_molecules["propanetricarboxylic-an49"]=2;repeated_molecules["propanetricarboxylic-an50"]=2
repeated_molecules["propanetricarboxylic-an51"]=2
repeated_molecules["propanetricarboxylic-2an1"]=2;repeated_molecules["propanetricarboxylic-2an2"]=2;repeated_molecules["propanetricarboxylic-2an3"]=2;repeated_molecules["propanetricarboxylic-2an4"]=2;repeated_molecules["propanetricarboxylic-2an5"]=2
repeated_molecules["propanetricarboxylic-2an6"]=2;repeated_molecules["propanetricarboxylic-2an7"]=2;repeated_molecules["propanetricarboxylic-2an8"]=2;repeated_molecules["propanetricarboxylic-2an9"]=2;repeated_molecules["propanetricarboxylic-2an10"]=2
repeated_molecules["propanetricarboxylic-2an11"]=2;repeated_molecules["propanetricarboxylic-2an12"]=2;repeated_molecules["propanetricarboxylic-2an13"]=2;repeated_molecules["propanetricarboxylic-2an14"]=2;repeated_molecules["propanetricarboxylic-2an15"]=2
repeated_molecules["propanetricarboxylic-2an16"]=2;repeated_molecules["propanetricarboxylic-2an17"]=2;repeated_molecules["propanetricarboxylic-2an18"]=2;repeated_molecules["propanetricarboxylic-2an19"]=2;repeated_molecules["propanetricarboxylic-2an20"]=2
repeated_molecules["propanetricarboxylic-2an21"]=2;repeated_molecules["propanetricarboxylic-2an22"]=2;repeated_molecules["propanetricarboxylic-2an23"]=2;repeated_molecules["propanetricarboxylic-2an24"]=2;repeated_molecules["propanetricarboxylic-2an25"]=2
repeated_molecules["propanetricarboxylic-2an16"]=2;repeated_molecules["propanetricarboxylic-2an27"]=2;repeated_molecules["propanetricarboxylic-2an28"]=2;repeated_molecules["propanetricarboxylic-2an29"]=2;repeated_molecules["propanetricarboxylic-2an30"]=2
repeated_molecules["propanetricarboxylic-2an21"]=2;repeated_molecules["propanetricarboxylic-2an32"]=2;repeated_molecules["propanetricarboxylic-2an33"]=2;repeated_molecules["propanetricarboxylic-2an34"]=2;repeated_molecules["propanetricarboxylic-2an35"]=2
repeated_molecules["butanetetracarboxylic-3an*"]=2
repeated_molecules["123triazole-neut"]=2
repeated_molecules["12phenylenediamine-cation*"]= 2
repeated_molecules["135benzenetricarboxylic-2an*"]= 3
repeated_molecules["135benzenetricarboxylic-an*"]=  3
repeated_molecules["13phenylenediamine-cation*"]=   2
repeated_molecules["13propanediamine_cation*"]=     2
repeated_molecules["14butanediamine_cation*"]=      2
repeated_molecules["14phenylenediamine_cation*"]=   2
repeated_molecules["22bipyridine_catio*"]=          2
repeated_molecules["22biquinoline-cation*"]=        2
repeated_molecules["23dimethylsuccinic_an*"]=       2
repeated_molecules["25dimethylpiperazine_cation*"]=  2
repeated_molecules["25dimethylpyrazine-cation*"]=    2
repeated_molecules["2aminoimidazole-neut*"]=         2
repeated_molecules["2aminopyrimidine-cation2"]=    2  
repeated_molecules["2hydroxypyrimidine-neut*"]=     2
repeated_molecules["2phbenzimidazole-neut*"]=       2
repeated_molecules["2phenylimidazole-neut*"]=       2
repeated_molecules["2phimidazole-neut*"]=       2       
repeated_molecules["23butanediamine-cation*"]=	   2
repeated_molecules["33bipyridine-cation*"]=         2
repeated_molecules["44bipyridine_cation*"]=         2
repeated_molecules["aminotetrazole-cation"]=2;repeated_molecules["aminotetrazole-cation3"]=2;repeated_molecules["aminotetrazole-cation4"]=2    
repeated_molecules["barbituric-an"]=     2  
repeated_molecules["benzimidazole-neut*"]=          2
repeated_molecules["biguanide-cation2*"]=           2
repeated_molecules["catechol-an*"]=                 2
repeated_molecules["catechol-neut"]=               2  
repeated_molecules["ciscyclohexan12dicarboxylic-an*"]=  2
repeated_molecules["cisethyleneoxidedicarboxylic-an*"]= 2
repeated_molecules["cyanuric-an*"]=    3
repeated_molecules["yclobutan11dicarboxylic-an*"]= 2
repeated_molecules["cyclobutan12cisdicarboxylic-an*"]= 2
repeated_molecules["cyclobutan12transdicarboxylic-an*"]= 2
repeated_molecules["cyclobutan13cisdicarboxylic-an*"]= 2
repeated_molecules["cyclobutan13transdicarboxylic-an*"]= 2
repeated_molecules["cyclohexan11dicarboxylic-an*"]=    2
repeated_molecules["cyclohexan14transdicarboxylic-an*"]=  2
repeated_molecules["cyclopentan11dicarboxylic-an*"]=  2
repeated_molecules["cyclopentan12transdicarboxylic-an*"]= 2
repeated_molecules["cyclopentan13transdicarboxylic-an*"]= 2
repeated_molecules["cyclopentan13cisdicarboxylic-an*"]= 2
repeated_molecules["cyclopropan11dicarboxylic-an*"]= 2
repeated_molecules["cyclopropan12cisdicarboxylic-an*"]= 2
repeated_molecules["cyclopropan12transdicarboxylic-an*"]= 2
repeated_molecules["DABCO-cation*"]=      2
repeated_molecules["dihydroxytartaric-an*"]= 2
repeated_molecules["dimethylmalonic-an*"]=  2
repeated_molecules["dimethylpiperazine-cation*"]= 2    
repeated_molecules["ethanedithiol_an*"]=   2
repeated_molecules["imidazole-neut*"]=     2
repeated_molecules["maleic-an*"]=          2
repeated_molecules["malonic-an*"]=         2
repeated_molecules["mesodibromosuccinic-an*"]= 2
repeated_molecules["meso23dimethylsuccinic-an*"]= 2
repeated_molecules["mesotartaric-an*"]=  2
repeated_molecules["mphtalic-an*"]=    2
repeated_molecules["ophtalic-an*"]=    2
repeated_molecules["oxalic-an*"]=      2
repeated_molecules["p-acetylphenol-neut*"]= 2
repeated_molecules["p-aminophenol-neut*"]= 2
repeated_molecules["p-aminophenol-cation*"]= 2
repeated_molecules["p-chlorobenzoic-neut*"]= 2
repeated_molecules["p-chlorophenol-neut*"]= 2
repeated_molecules["p-chlorophenolbenzoic-neut*"]= 2
repeated_molecules["p-cyanobenzoic-neut*"]= 2
repeated_molecules["p-cyanophenol-neut*"]= 2
repeated_molecules["p-fluorobenzoic-neut*"]= 2
repeated_molecules["p-fluorophenol-neut*"]= 2
repeated_molecules["p-hydroxybenzoic-neut*"]= 2
repeated_molecules["p-hydroxybenzoic-an*"]= 2
repeated_molecules["p-hydroxyphenol-an*"]= 2
repeated_molecules["p-hydroxyphenol-neut*"]= 2
repeated_molecules["p-mercaptophenol-neut*"]= 2
repeated_molecules["p-mercaptophenol-an*"]= 2
repeated_molecules["p-methoxypbenzoic-neut*"]= 2
repeated_molecules["p-methylphenol-neut*"]= 2
repeated_molecules["p-nitrobenzoic-neut*"]= 2
repeated_molecules["p-nitrophenoln-neut*"]= 2
repeated_molecules["p-phenylphenol-neut*"]= 2
repeated_molecules["parabanic-an*"]= 2
repeated_molecules["pbenzbetaine-neut*"]= 2
repeated_molecules["perhydrodiphenic_an*"]= 2
repeated_molecules["perimidine-neut*"]= 2
repeated_molecules["phenazine-cation*"]= 2
repeated_molecules["phenol-neut*"]= 2
repeated_molecules["phtalazine-cation*"]= 2
repeated_molecules["picric_neut*"]= 2
repeated_molecules["pphenoxybenzoic-neut*"]= 2
repeated_molecules["pphtalic-an*"]= 2
repeated_molecules["pthiocresol-neut*"]= 2
repeated_molecules["ptoluic-neut*"]=  2
repeated_molecules["ptolylphosphonic-an*"]= 2
repeated_molecules["ptolylphosphonic-neut*"]= 2
repeated_molecules["pyrazine-cation*"]=  2
repeated_molecules["pyrazole-neut*"]= 2
repeated_molecules["pyrimidine-cation*"]= 2
repeated_molecules["rubeanic-an*"]= 2
repeated_molecules["sparteine-cation*"]= 2
repeated_molecules["squaric-an*"] = 4
repeated_molecules["squaric-neut*"] = 2
repeated_molecules["succinic-an*"] =2
repeated_molecules["tartaric_an*"] =2
repeated_molecules["tetramethylethylenediamine-cation*"]  =2
repeated_molecules["tetramethylpyrazine-cation*"] =2
repeated_molecules["tetramethylsuccinic-an*"] =2
repeated_molecules["tetrazole-neut*"] =2
repeated_molecules["thiabendazole-cation*"] =2
repeated_molecules["thiabendazole-neut*"] =2
repeated_molecules["thiodiacetic-an*"] =2
repeated_molecules["thiophenol-neut*"] =2
repeated_molecules["thiourea-cation*"] =2
repeated_molecules["thiophenol-neut*"] =2
repeated_molecules["trans12cyclohexanedicarboxylic-an*"] = 2
repeated_molecules["trans4cyclohexene12dicarboxylic-an*"] = 2
repeated_molecules["transcyclohexanediamine-cation*"] = 2
repeated_molecules["transethyleneoxidedicarboxylic-an*"] = 2
repeated_molecules["tropolone-cation"] = 2 
repeated_molecules["tropolone-neut*"] = 2
repeated_molecules["veronal-an*"] =   2
repeated_molecules["urea-cation*"] = 2
repeated_molecules["tetramethylurea-cation*"] = 2
repeated_molecules["hydroxytropolone-an1"] = 2; repeated_molecules["hydroxytropolone-an2"] = 2
repeated_molecules["hydroxytropolone-neut3"] = 2;repeated_molecules["hydroxytropolone-neut4"] = 2;repeated_molecules["hydroxytropolone-neut5"] = 2
repeated_molecules["pyrazole-neut*"] =   2
repeated_molecules["benzotriazole-cation"] =  2 
repeated_molecules["benzotriazole-neut"] =  2 
repeated_molecules["paracetamol-neut*"] = 2
repeated_molecules["55dichlorobarbituric-an*"] = 2
repeated_molecules["55dibromobarbituric-an*"] = 2
repeated_molecules["55diphenylbarbituric-an*"] = 2
repeated_molecules["55cyclopropanlbarbituric-an*"] = 2
repeated_molecules["55cyclobutanlbarbituric-an*"] = 2
repeated_molecules["55cyclopentanlbarbituric-an*"] = 2
repeated_molecules["55cyclohexanlbarbituric-an*"] = 2
repeated_molecules["allobarbital*"] =  2
repeated_molecules["diphenic_an*"] = 2
repeated_molecules["4pyridinecarboxylic-neut*"] = 2
repeated_molecules["4pyridinecarboxylic-cation*"] = 2
repeated_molecules["methyl4hydroxybenzoate-neut*"] = 2
repeated_molecules["35diacetamido124triazole-neut*"] = 2
repeated_molecules["35ditrifluoroacetamido124triazole-neut*"] = 2
repeated_molecules["35dibenzamido124triazole-neut*"] = 2
repeated_molecules["35diparanitrobenzamido124triazole-neut*"] = 2
repeated_molecules["ioxynil-neut*"] = 2
repeated_molecules["pentachlorophenol-neut*"] = 2
repeated_molecules["56difluorobenzimidazole-neut*"] = 2
repeated_molecules["4567tetrafluorobenzimidazole-neut*"] = 2
repeated_molecules["4mercaptopyridine-cation*"] = 2
repeated_molecules["18dimethylaminonaphtalene-cation*"] = 2
repeated_molecules["18dimethylamino27dimethoxynaphtalene-cation*"] = 2
repeated_molecules["159triazaciclododecane-2cation*"] = 3
repeated_molecules["159triazaciclododecane-cation*"] = 3
repeated_molecules["7methyl159triazabicyclo550dodecane-2cation*"] = 3
repeated_molecules["7methyl159triazabicyclo550dodecane-cation*"] = 3
repeated_molecules["NNNtrimethyl159triazaciclododecane-cation*"] = 3
repeated_molecules["NNNtrimethyl159triazaciclododecane-2cation*"] = 3
repeated_molecules["159trizabicyco733pentadecane-2cation*"] =   2
repeated_molecules["159trizabicyco733pentadecane-cation2100"]=2;repeated_molecules["159trizabicyco733pentadecane-cation2101"]=2;repeated_molecules["159trizabicyco733pentadecane-cation2102"]=2
repeated_molecules["159trizabicyco733pentadecane-cation2103"]=2;repeated_molecules["159trizabicyco733pentadecane-cation2104"]=2;repeated_molecules["159trizabicyco733pentadecane-cation2105"]=2
repeated_molecules["159trizabicyco733pentadecane-cation2106"]=2;repeated_molecules["159trizabicyco733pentadecane-cation2107"]=2;repeated_molecules["159trizabicyco733pentadecane-cation2108"]=2
repeated_molecules["159trizabicyco733pentadecane-cation2109"]=2;repeated_molecules["159trizabicyco733pentadecane-cation2110"]=2;repeated_molecules["159trizabicyco733pentadecane-cation2111"]=2
repeated_molecules["159trizabicyco733pentadecane-cation2112"]=2;repeated_molecules["159trizabicyco733pentadecane-cation2113"]=2;repeated_molecules["159trizabicyco733pentadecane-cation2114"]=2
repeated_molecules["159trizabicyco733pentadecane-cation2115"]=2;repeated_molecules["159trizabicyco733pentadecane-cation2116"]=2;repeated_molecules["159trizabicyco733pentadecane-cation2117"]=2
repeated_molecules["159trizabicyco733pentadecane-cation2118"]=2;repeated_molecules["159trizabicyco733pentadecane-cation2119"]=2;repeated_molecules["159trizabicyco733pentadecane-cation2120"]=2
repeated_molecules["159trizabicyco733pentadecane-cation2121"]=2;repeated_molecules["159trizabicyco733pentadecane-cation2122"]=2;repeated_molecules["159trizabicyco733pentadecane-cation2123"]=2
repeated_molecules["159trizabicyco733pentadecane-cation2124"]=2;repeated_molecules["159trizabicyco733pentadecane-cation2125"]=2;repeated_molecules["159trizabicyco733pentadecane-cation2126"]=2
repeated_molecules["159trizabicyco733pentadecane-cation2127"]=2;repeated_molecules["159trizabicyco733pentadecane-cation2128"]=2;repeated_molecules["159trizabicyco733pentadecane-cation2129"]=2
repeated_molecules["159trizabicyco733pentadecane-cation2130"]=2;repeated_molecules["159trizabicyco733pentadecane-cation2131"]=2;repeated_molecules["159trizabicyco733pentadecane-cation2132"]=2
repeated_molecules["147triazacyclononane_cation*"] =  3
repeated_molecules["147triazacyclononane_2cation*"] =  3
repeated_molecules["NNNtrimethyl147triazacyclononane_cation*"] = 3
repeated_molecules["NNNtrimethyl147triazacyclononane_2cation*"] = 3
repeated_molecules["36dichloropyridazine-cation*"] = 2
repeated_molecules["1456tetrahydropyrimidine-neut*"] = 2
repeated_molecules["2amino1456tetrahydropyrimidine-neut1"] = 2
repeated_molecules["2methoxy1456tetrahydropyrimidine-neut*"] = 2
repeated_molecules["2phenyl1456tetrahydropyrimidine-neut*"] = 2
repeated_molecules["5methoxy1456tetrahydropyrimidine-neut*"] = 2
repeated_molecules["5hydroxy1456tetrahydropyrimidine-neut*"] = 2
repeated_molecules["5hydroxy2methyl1456tetrahydropyrimidine-neut*"] = 2
repeated_molecules["2amino5bromopyrimidine-cation*"] = 2
repeated_molecules["2amino5bromo46dimethylpyrimidine-cation*"] = 2
repeated_molecules["2amino5cyano46dimethylpyrimidine-cation*"] = 2
repeated_molecules["2amino46diphenylpyrimidine-cation*"] = 2
repeated_molecules["2amino5iodopyrimidine-cation*"] = 2
repeated_molecules["5bromo2methoxypyrimidine-cation*"] = 2
repeated_molecules["5bromo2methylthiopyrimidine-cation*"] = 2
repeated_molecules["5bromo2methylaminopyrimidine-cation*"] = 2
repeated_molecules["4acetamidopyrimidine-cation*"] = 2
repeated_molecules["5bromo2hydroxypyrimidine-cation*"] = 2
repeated_molecules["5bromo2hydroxypyrimidine-neut*"] = 2
repeated_molecules["5bromo2mercaptopyrimidine-cation*"] = 2
repeated_molecules["46diaminopyrimidine-cation*"] = 2
repeated_molecules["46diamino5bromopyrimidine-cation*"] = 2
repeated_molecules["46diamino25dimethyl-cation*"] = 2
repeated_molecules["46dihydroxypyrimidine-cation3"] = 2; repeated_molecules["46dihydroxypyrimidine-cation4"] = 2;  repeated_molecules["46dihydroxypyrimidine-cation5"] = 2; repeated_molecules["46dihydroxypyrimidine-cation6"] = 2
repeated_molecules["46dihydroxypyrimidine-neut1"] = 2;repeated_molecules["46dihydroxypyrimidine-neut2"] = 2;repeated_molecules["46dihydroxypyrimidine-neut3"] = 2;repeated_molecules["46dihydroxypyrimidine-neut5"] = 2
repeated_molecules["46dihydroxypyrimidine-an*"]=2
repeated_molecules["46dimercaptopyrimidine-cation3"]=2; repeated_molecules["46dimercaptopyrimidine-cation4"]=2; repeated_molecules["46dimercaptopyrimidine-cation5"]=2;repeated_molecules["46dimercaptopyrimidine-cation6"]=2  
repeated_molecules["46dimercaptopyrimidine-neut1"]=2;repeated_molecules["46dimercaptopyrimidine-neut2"]=2;repeated_molecules["46dimercaptopyrimidine-neut3"]=2;repeated_molecules["46dimercaptopyrimidine-neut4"]=2 
repeated_molecules["246triaminopyrimidine-cation1*"] =   2
repeated_molecules["27diaminoacridine-cation2"] =  2 
repeated_molecules["27dimethoxy18dimorpholinonaphtalene-cation*"] = 2
repeated_molecules["18dimorpholinonaphtalene-cation*"] = 2
repeated_molecules["23diaminopyrazine-cation*"] =  2   
repeated_molecules["23diaminoquinoxaline-cation*"] =  2 
repeated_molecules["23diamino56dimethylpyrazine-cation*"] = 2
repeated_molecules["1278tetradimethylaminonaphtalene-cation*"] = 2
repeated_molecules["15naphtyridine-cation*"] =   2
repeated_molecules["meldrumsacid-neut2"] = 2 ;repeated_molecules["meldrumsacid-neut3"] = 2 
repeated_molecules["dimedone-neut2"]=2;repeated_molecules["dimedone-neut3"]=2;  
repeated_molecules["pyridine26dimethyl35dicarboxylic-an2"]=2; repeated_molecules["pyridine26dimethyl35dicarboxylic-an1"]=2
repeated_molecules["pyridine26dimethyl35dicarboxylic-neut5"]=2;repeated_molecules["pyridine26dimethyl35dicarboxylic-neut6"]=2;  
repeated_molecules["pyridine35dicarboxylic-an1"]=2; repeated_molecules["pyridine35dicarboxylic-an1"]=3; 
repeated_molecules["pyridine35dicarboxylic-neut4"]=2; repeated_molecules["pyridine35dicarboxylic-neut5"]=2
repeated_molecules["pyridine246trimethyl35dicarboxylic-an1"]=2; repeated_molecules["pyridine246trimethyl35dicarboxylic-an2"]=2
repeated_molecules["pyridine246trimethyl35dicarboxylic-neut4"]=2; repeated_molecules["pyridine246trimethyl35dicarboxylic-neut5"]=2 
repeated_molecules["chelidamic-2an3"]=2;repeated_molecules["chelidamic-2an4"]=2;repeated_molecules["chelidamic-2an5"]=2   
repeated_molecules["chelidamic-an1"]=2;repeated_molecules["chelidamic-an2"]=2;repeated_molecules["chelidamic-an3"]=2;repeated_molecules["chelidamic-an4"]=2
repeated_molecules["chelidamic-an5"]=2;repeated_molecules["chelidamic-an6"]=2;repeated_molecules["chelidamic-an9"]=2 
repeated_molecules["pyridine345tricarboxylic-2an1"]=2;repeated_molecules["pyridine345tricarboxylic-2an10"]=2  
repeated_molecules["pyridine345tricarboxylic-an1"]=2;repeated_molecules["pyridine345tricarboxylic-an3"]=2;repeated_molecules["pyridine345tricarboxylic-an4"]=2 
repeated_molecules["pyridine345tricarboxylic-neut4"]=2;repeated_molecules["pyridine345tricarboxylic-neut5"]=2 
repeated_molecules["cubane14dicarboxylic-an*"]=2
repeated_molecules["cubane2chloro14dicarboxylic-an*"]= 2
repeated_molecules["cubane23dichloro14dicarboxylic-an*"]= 2
repeated_molecules["cubane27dichloro14dicarboxylic-an*"]= 2
repeated_molecules["pbenzoquinonediimine-cation*"]= 2
repeated_molecules["5carboxylictropolone-an*"]= 2
repeated_molecules["5carboxylictropolone-neut*"]=  2
repeated_molecules["5nitrotropolone-neut*"]= 2
repeated_molecules["18dipyrrolidinnaphthalene-cation*"]= 2
repeated_molecules["RSbicyclo222oct5ene23dicarboxylic-an*"]= 2
repeated_molecules["18diaminonaphtalene-cation*"]= 2
repeated_molecules["18dimeaminonaphtalene-cation*"]= 2
repeated_molecules["1234tetrahydronaphtho18ef14diazepine-cation*"]= 2
repeated_molecules["tetrahydro36pyridazinedione-an*"]= 2
repeated_molecules["benzoccinnoline-cation*"]= 2
repeated_molecules["1458tetraazaphenanthrene-cation1*"]= 2
repeated_molecules["naphtimidazole-neut*"]= 2
repeated_molecules["47phenanthroline-cation*"]= 2
repeated_molecules["2methylnaphtimidazole-neut*"]= 2
repeated_molecules["38dimethyl110phenanthroline-cation*"]= 2
repeated_molecules["3568tetramethyl110phenanthroline-cation*"]= 2
repeated_molecules["38dibromo110phenanthroline-cation*"]= 2
repeated_molecules["56dichloro110phenanthroline-cation*"]= 2
repeated_molecules["47dichloro110phenanthroline-cation*"]= 2
repeated_molecules["29dimethyl110phenanthroline-cation*"]= 2
repeated_molecules["3478tetramethyl110phenanthroline-cation*"]= 2
repeated_molecules["2479tetramethyl110phenanthroline-cation*"]= 2
repeated_molecules["47dimethoxy110phenanthroline-cation*"]= 2
repeated_molecules["56dimethoxy110phenanthroline-cation*"]= 2
repeated_molecules["parabanic-an*"]= 2
repeated_molecules["hexamethylenetetramine-cation*"]= 4
repeated_molecules["114diaza6helicene-cation*"]= 2
repeated_molecules["114diaza5helicene-cation*"]= 2
repeated_molecules["16diazabicyclo440decane-cation*"]= 2
repeated_molecules["16diazabicyclo440decane-neut3"]=2
repeated_molecules["23dimethyl23diazabicyclo221heptane-cation*"]= 2
repeated_molecules["23dimethyl23diazabicyclo221heptane-cation*"]= 2
repeated_molecules["12dimethylpyrazolidine-cation*"]= 2
repeated_molecules["hexahydropyrazolo12apyrazole-cation*"]= 2
repeated_molecules["12dimethylhexahydropyridazine_cation*"]= 2
repeated_molecules["dimethylhydrazine-cation*"]= 2
repeated_molecules["hydrazine-cation*"]= 2
repeated_molecules["12diazepine12dimethylhexahydro-cation*"]= 2
repeated_molecules["tetramethylhydrazine-cation*"]= 2
repeated_molecules["12dimethyl1236tetrahydropyridazine-cation*"]= 2
repeated_molecules["NNpbipyrrolidine-cation*"]= 2
repeated_molecules["NNpbipiridine-cation*"]= 2
repeated_molecules["36dimercaptopyridazine-neut1"]=2
repeated_molecules["36dimercaptopyridazine-neut6"]=2
repeated_molecules["36dimercaptopyridazine-neut5"]=2
repeated_molecules["36dimercaptopyridazine-an*"]=2
repeated_molecules["2chloroimidazole-neut"]=2
repeated_molecules["11bistrifluoromethylethanol-neut1"]=2
repeated_molecules["12dimethylurazole-neut2"]=2
repeated_molecules["6aminopenicilanic-an2"]=2
repeated_molecules["45dimethoxy18dimethylaminonpahtalene-cation*"]=2
repeated_molecules["cyclopentadiene-neut"]=5
repeated_molecules["cyclopenta25dien1carbonitrile-neut2"]=2
repeated_molecules["cyclopenta25dien1carbonitrile-neut2"]=3

repeated_molecules["2aminopyrimidin5ylphosphonic-an10*"]=2
repeated_molecules["2aminopyrimidin5ylphosphonic-neut100*"]=2
repeated_molecules["2hydroxypyrimidin5ylphosphonic-2an*"]=2
repeated_molecules["2hydroxypyrimidin5ylphosphonic-an10*"]=2
repeated_molecules["2hydroxypyrimidin5ylphosphonic-an"]=2
repeated_molecules["2hydroxypyrimidin5ylphosphonic-an2"]=2
repeated_molecules["2hydroxypyrimidin5ylphosphonic-an3"]=2
repeated_molecules["2hydroxypyrimidin5ylphosphonic-an4"]=2
repeated_molecules["2hydroxypyrimidin5ylphosphonic-an5"]=2
repeated_molecules["2hydroxypyrimidin5ylphosphonic-neut1001"]=2
repeated_molecules["2hydroxypyrimidin5ylphosphonic-neut1002"]=2
repeated_molecules["2hydroxypyrimidin5ylphosphonic-neut1003"]=2
repeated_molecules["2hydroxypyrimidin5ylphosphonic-neut1004"]=2

repeated_molecules["2methyl13cyclohexanedione-neut2"]=2
repeated_molecules["2methyl13cyclohexanedione-neut3"]=2

repeated_molecules["ammelide-an1"]=2
repeated_molecules["ammelide-cation5"]=2
repeated_molecules["ammelide-cation8"]=2
repeated_molecules["ammelide-cation12"]=2
repeated_molecules["ammeline-neut1"]=2
repeated_molecules["biuret-neut2"]=2
repeated_molecules["biuret-neut3"]=2
repeated_molecules["47difluoro1hbenzimidazole-neut"]=2
repeated_molecules["2piperazin1ylpyrimidine-cation3"]=2
repeated_molecules["melamine-cation3"]=3

repeated_molecules["cyclopropan11dicarboxylic-an12"]= 2
repeated_molecules["cyclopropan11dicarboxylic-neut6"]= 2
repeated_molecules["cyclopropan11dicarboxylic-2an"]= 2
repeated_molecules["cyclopropan11dicarboxylic-2an3"]= 2
repeated_molecules["cyclopropan11dicarboxylic-2an11"]= 2

repeated_molecules["1methoxypyridin4one-cation"]=2
repeated_molecules["1nitro23indanone-neut3"]=2
repeated_molecules["1nitro23indanone-neut4"]=2
repeated_molecules["1nitro23indanone-neut11"]=2
repeated_molecules["1nitro23indanone-neut12"]=2

repeated_molecules["1s2r3scis123trimecyclpropdicarbxylic-an*"]=2
repeated_molecules["1s2r3scis123trimecyclpropdicarbxylic-an*"]=2
repeated_molecules["2aminoindan-neut1"]=2
repeated_molecules["2aminopyridinenoxide-cation1"]=2
repeated_molecules["2aminotropone-cation2"]=2
repeated_molecules["2bromoimidazole-neut"]=2
repeated_molecules["2dimeaminopyridinenoxide-cation1"]=2
repeated_molecules["2hidroxypyrimidinenoxide-cation1*"]=2
repeated_molecules["2hidroxypyrimidinenoxide-neut2"]=2
repeated_molecules["2meaminopyridinenoxide-cation1"]=2
repeated_molecules["2mercaptobenzimidazole-an"]=2
repeated_molecules["2mercaptobenzimidazole-an2"]=2
repeated_molecules["2mercaptobenzimidazole-neut2"]=2
repeated_molecules["2mercaptobenzimidazole-neut3"]=2
repeated_molecules["2methoxypyrimidinenoxide-cation"]=2
repeated_molecules["2methylbenzimidazole-neut"]=2
repeated_molecules["2methylindanone-neut2"]=2
repeated_molecules["2methylindanone-neut3"]=2
repeated_molecules["3me135triazine241H3Hdione-neut1"]=2
repeated_molecules["4aminopyridinenoxide-cation1"]=2
repeated_molecules["4aminopyridinenoxide-neut1"]=2
repeated_molecules["4bromobenzylamine-neut2"]=2
repeated_molecules["4bromobenzylamine-cation1"]=2  
repeated_molecules["4diazoniobenzoaten-cation"]=2
repeated_molecules["4dimeaminopyridinenoxide-cation1"]=2
repeated_molecules["4hydroxypyrimidinenoxide-cation"]=2
repeated_molecules["4meaminopyridinenoxide-cation2"]=2
repeated_molecules["4meaminopyridinenoxide-cation2"]=2
repeated_molecules["4methoxypyridinenoxide-cation"]=2
repeated_molecules["4methoxypyrimidinenoxide-cation"]=2
repeated_molecules["4nitrobenzenethiol-neut"]=2
repeated_molecules["4nmeacetamidopyridinenoxide-cation1"]=2
repeated_molecules["4nmeacetamidopyridinenoxide-cation3"]=2
repeated_molecules["4nmeacetamidopyridinenoxide-cation1"]=2
repeated_molecules["5azauracil-an2"]=2
repeated_molecules["5azauracil-neut1"]=2
repeated_molecules["5hydroxytropolone-an1"]=2
repeated_molecules["5hydroxytropolone-an2"]=2
repeated_molecules["5hydroxytropolone-neut1"]=2
repeated_molecules["5hydroxytropolone-neut3"]=2
repeated_molecules["5hydroxytropolone-neut4"]=2
repeated_molecules["5hydroxytropolone-neut5"]=2
repeated_molecules["5hydroxytropolone-neut6"]=2
repeated_molecules["5methyltropolone-neut1"]=2
repeated_molecules["5methyltropolone-neut2"]=2
repeated_molecules["6me135triazine241H3Hdione-an1"]=2
repeated_molecules["6me135triazine241H3Hdione-neut1"]=2
repeated_molecules["6me135triazine241H3Hdione-neut4"]=2
repeated_molecules["6me135triazine241H3Hdione-neut5"]=2
repeated_molecules["6me135triazine241H3Hdione-neut6"]=2
repeated_molecules["23dihydroxyquinoxaline-an*"]=2
repeated_molecules["23dihydroxyquinoxaline-neut2"]=2
repeated_molecules["23dihydroxyquinoxaline-neut3"]=2
repeated_molecules["23dihydroxyquinoxaline-neut4"]=2
repeated_molecules["26dibromo7oh3methyltropolone-neut*"]=2
repeated_molecules["26dibromo7oh4methyltropolone-neut*"]=2
repeated_molecules["26dimethyl4hpyran4one-cation"]=2
repeated_molecules["26diphenyl4hpyran4one-cation"]=2
repeated_molecules["33dimecis12cyclpropdicarbxylic-an*"]=2
repeated_molecules["33dimetrans12cyclpropdicarbxylic-an*"]=2
repeated_molecules["34thiophenedicarboxylic-an*"]=2
repeated_molecules["45imidazoledicarboxylic-2an*"]=2
repeated_molecules["45imidazoledicarboxylic-an*"]=2
repeated_molecules["222tripyridine-2cation1"]=2
repeated_molecules["222tripyridine-2cation5"]=2
repeated_molecules["222tripyridine-2cation6"]=2
repeated_molecules["222tripyridine-2cation7"]=2
repeated_molecules["222tripyridine-2cation8"]=2
repeated_molecules["222tripyridine-2cation9"]=2
repeated_molecules["222tripyridine-cation1"]=2
repeated_molecules["222tripyridine-cation2"]=2
repeated_molecules["222tripyridine-cation3"]=2
repeated_molecules["222tripyridine-cation4"]=2
repeated_molecules["222tripyridine-cation5"]=2
repeated_molecules["222tripyridine-cation6"]=2
repeated_molecules["222tripyridine-cation7"]=2
repeated_molecules["222tripyridine-cation9"]=2
repeated_molecules["222tripyridine-cation10"]=2
repeated_molecules["222tripyridine-cation11"]=2

repeated_molecules["ammelide-an2"]=2
repeated_molecules["ammelide-an3"]=2
repeated_molecules["ammelide-an4"]=2
repeated_molecules["ammelide-cation10"]=2
repeated_molecules["ammelide-cation11"]=2
repeated_molecules["ammelide-cation12"]=2
repeated_molecules["ammelide-neut1"]=2
repeated_molecules["ammeline-cation1"]=2
repeated_molecules["ammeline-neut1"]=2
repeated_molecules["ammeline-neut3"]=2
repeated_molecules["bicyclo221heptane2ene23dicarboxylic-an*"]=2
repeated_molecules["bicyclo221heptane2ene23dicarboxylic-neut2"]=2
repeated_molecules["bicyclo221heptane2ene23dicarboxylic-neut3"]=2
repeated_molecules["bicyclo221heptane14dicarboxylic-an*"]=2
repeated_molecules["bicyclo221heptane25diene23dicarboxylic_2an2"]=2
repeated_molecules["bicyclo221heptane25diene23dicarboxylic_2an3"]=2
repeated_molecules["bicyclo221heptane25diene23dicarboxylic-an*"]=2
repeated_molecules["bicyclo221heptane25diene23dicarboxylic-neut2"]=2
repeated_molecules["bicyclo221heptane25diene23dicarboxylic-neut3"]=2
repeated_molecules["bicyclo221heptane25diene23dicarboxylic-neut4"]=2
repeated_molecules["bicyclo222octane14diarboxylic-an1"]=2
repeated_molecules["bispidine-cation"]=2
repeated_molecules["bispidine-neut2"]=2
repeated_molecules["cis12dime12cyclpropdicarbxylic-an*"]=2
repeated_molecules["cis12dime12cyclpropdicarbxylic-neut2"]=2
repeated_molecules["cyclohexa14diene12dicarboxyli-an*"]=2
repeated_molecules["cyclohexa14diene12dicarboxyli-neut2"]=2
repeated_molecules["cyclohexa14diene12dicarboxyli-neut3"]=2
repeated_molecules["cyclohexa15diene12dicarboxyli-an*"]=2
repeated_molecules["cyclohexa15diene12dicarboxyli-neut*"]=2
repeated_molecules["cyclopent1ene12dicarboxylic-an*"]=2
repeated_molecules["cyclopent1ene12dicarboxylic-neut*"]=2
repeated_molecules["furan15dicarboxylic-an*"]=2
repeated_molecules["furan15dicarboxylic-neut2"]=2
repeated_molecules["furan15dicarboxylic-neut3"]=2
repeated_molecules["furan15dicarboxylic-neut4"]=2
repeated_molecules["furan34dicarboxylic-an*"]=2
repeated_molecules["furan34dicarboxylic-neut2"]=2
repeated_molecules["furan34dicarboxylic-neut3"]=2
repeated_molecules["furantetracarboxylic-2an27"]=2
repeated_molecules["furantetracarboxylic-2an31"]=2
repeated_molecules["furantetracarboxylic-2an37"]=2
repeated_molecules["furantetracarboxylic-2an210"]=2
repeated_molecules["furantetracarboxylic-2an216"]=2
repeated_molecules["furantetracarboxylic-2an217"]=2
repeated_molecules["furantetracarboxylic-2an310"]=2
repeated_molecules["furantetracarboxylic-2an311"]=2
repeated_molecules["furantetracarboxylic-2an314"]=2
repeated_molecules["furantetracarboxylic-3an*"]=2
repeated_molecules["furantetracarboxylic-an1*"]=2
repeated_molecules["imidazole2thiol-an"]=2
repeated_molecules["imidazole2thiol-cation"]=2
repeated_molecules["nhydroxyglutarimide-neut"]=2
repeated_molecules["Nhydroxypyridine4thione-cation1"]=2
repeated_molecules["Nhydroxypyridine4thione-neut1"]=4
repeated_molecules["Nhydroxypyridine4thione-neut2"]=2
repeated_molecules["nhydroxysuccinimide-neut"]=2
repeated_molecules["NOH5norbornene23dicarboximide-neut"]=2
repeated_molecules["NOH5norbornene23dicarboximide-neut2"]=2
repeated_molecules["NOH5norbornene23dicarboximide-neut3"]=2
repeated_molecules["pyrithione-cation1"]=2
repeated_molecules["pyrithione-cation2"]=2
repeated_molecules["trans12dime12cyclpropdicarbxylic-an"]=2
repeated_molecules["nndimethylethyldenediamine-neut4"]=2
repeated_molecules["nndimethylethyldenediamine-neut5"]=2
repeated_molecules["nndimethylethyldenediamine-neut6"]=2
repeated_molecules["nndimethylethyldenediamine-neut7"]=2
repeated_molecules["nndimethylethyldenediamine-neut8"]=2
repeated_molecules["nndimethylethyldenediamine-neut9"]=2
repeated_molecules["nndimethylethyldenediamine-2cation2"]=2
repeated_molecules["nndimethylethyldenediamine-2cation3"]=2
repeated_molecules["nndimethylethyldenediamine-cation24"]=2
repeated_molecules["nndimethylethyldenediamine-cation25"]=2
repeated_molecules["nndimethylethyldenediamine-cation26"]=2
repeated_molecules["nndimethylethyldenediamine-cation27"]=2
repeated_molecules["nndimethylethyldenediamine-cation28"]=2
repeated_molecules["nndimethylethyldenediamine-cation29"]=2
repeated_molecules["methylthioethylamine-neut2"]=2
repeated_molecules["methylthioethylamine-neut4"]=2
repeated_molecules["methylthioethylamine-neut5"]=2
repeated_molecules["methylthioethylamine-neut6"]=2
repeated_molecules["methylthioethylamine-neut7"]=2
repeated_molecules["methylthioethylamine-neut8"]=2
repeated_molecules["methylthioethylamine-neut9"]=2
repeated_molecules["methylthioethylamine-neut10"]=2
repeated_molecules["methylthioethylamine-neut11"]=2
repeated_molecules["methylthioethylamine-cation2"]=2
repeated_molecules["methylthioethylamine-cation3"]=2
repeated_molecules["methylthioethylamine-cation4"]=2
repeated_molecules["nphenylethylenediamine-2cation2"]=2
repeated_molecules["nphenylethylenediamine-neut6"]=2
repeated_molecules["nphenylethylenediamine-neut5"]=2
repeated_molecules["nphenylethylenediamine-neut4"]=2
repeated_molecules["nphenylethylenediamine-cation2"]=2
repeated_molecules["2aminoethylacetate-neut11"]=2
repeated_molecules["2aminoethylacetate-neut10"]=2
repeated_molecules["2aminoethylacetate-neut9"]=2
repeated_molecules["2aminoethylacetate-neut8"]=2
repeated_molecules["2aminoethylacetate-neut7"]=2
repeated_molecules["2aminoethylacetate-neut6"]=2
repeated_molecules["2aminoethylacetate-neut5"]=2
repeated_molecules["2aminoethylacetate-neut4"]=2
repeated_molecules["2aminoethylacetate-neut3"]=2
repeated_molecules["2aminoethylacetate-cation2"]=2
repeated_molecules["2aminoethylacetate-cation3"]=2
repeated_molecules["2aminoethylacetate-cation4"]=2
repeated_molecules["propionamide-neut2"]=2
repeated_molecules["propionamide-cation4"]=2
repeated_molecules["propionamide-cation3"]=2
repeated_molecules["nndimethylethylamine-neut2"]=2
repeated_molecules["nndimethylethylamine-cation2"]=2
repeated_molecules["333trichloro1aminopropane-neut3"]=2
repeated_molecules["333trichloro1aminopropane-neut4"]=2
repeated_molecules["333trichloro1aminopropane-neut5"]=2
repeated_molecules["333trichloro1aminopropane-cation2"]=2
repeated_molecules["nbutylamide-cation10"]=2
repeated_molecules["nbutylamide-cation9"]=2
repeated_molecules["nbutylamide-cation8"]=2
repeated_molecules["nbutylamide-cation7"]=2
repeated_molecules["nbutylamide-cation6"]=2
repeated_molecules["nbutylamide-cation5"]=2
repeated_molecules["nbutylamide-cation4"]=2
repeated_molecules["nbutylamide-cation3"]=2
repeated_molecules["nbutylamide-neut2"]=2
repeated_molecules["nbutylamide-neut3"]=2
repeated_molecules["nbutylamide-neut4"]=2
repeated_molecules["nbutylamide-neut5"]=2
repeated_molecules["4dimeamino22diphebutanenitrile-neut2"]=2
repeated_molecules["4dimeamino22diphebutanenitrile-cation2"]=2
repeated_molecules["22dimethyl13propanediamine-neut*"]=2
repeated_molecules["12propanediamine-neut*"]=2
repeated_molecules["3tbutylaminopropan2ol-neut12"]=2
repeated_molecules["3tbutylaminopropan2ol-neut11"]=2
repeated_molecules["3tbutylaminopropan2ol-neut10"]=2
repeated_molecules["3tbutylaminopropan2ol-neut9"]=2
repeated_molecules["3tbutylaminopropan2ol-neut8"]=2
repeated_molecules["3tbutylaminopropan2ol-neut7"]=2
repeated_molecules["3tbutylaminopropan2ol-cation4"]=2
repeated_molecules["3tbutylaminopropan2ol-cation5"]=2
repeated_molecules["3tbutylaminopropan2ol-cation6"]=2
repeated_molecules["nndimethylallylamine-cation"]=2
repeated_molecules["nndimethylallylamine-neut"]=2
repeated_molecules["propargylamine-neut1"]=2
repeated_molecules["3dimethylamino1propyne-cation1"]=2
repeated_molecules["3dimethylamino1propyne-neut1"]=2
repeated_molecules["ggdimethylvaleramide-cation3"]=2
repeated_molecules["ggdimethylvaleramide-cation4"]=2
repeated_molecules["ggdimethylvaleramide-neut"]=2
repeated_molecules["methylcyclopentylamine-neut3"]=2
repeated_molecules["methylcyclopentylamine-neut2"]=2
repeated_molecules["methylcyclopentylamine-neut1"]=2
repeated_molecules["methylcyclopentylamine-cation1"]=2
repeated_molecules["1mecyclohexylamine-neut1"]=2
repeated_molecules["1mecyclohexylamine-neut4"]=2
repeated_molecules["trans4mecyclohexylamine-neut2"]=2
repeated_molecules["cyclohexanimine-neut"]=2
repeated_molecules["nmecyclohexanimine-neut"]=2
repeated_molecules["nacetobenzenesulfonamide-an1"]=2
repeated_molecules["nacetobenzenesulfonamide-neut2"]=2
repeated_molecules["nacetobenzenesulfonamide-an2"]=2
repeated_molecules["nacetobenzenesulfonamide-an3"]=2
repeated_molecules["44pdiaminobenzophenone-cation"]=2
repeated_molecules["46diaminoresorcinol-cation*"]=2
repeated_molecules["46diaminoresorcinol-neut*"]=2
repeated_molecules["46diaminoresorcinol-an*"]=2
repeated_molecules["26diaminophenol-neut"]=2
repeated_molecules["26diaminophenol-cation1"]=2
repeated_molecules["26diaminophenol-cation2"]=2
repeated_molecules["26diaminophenol-cation3"]=2
repeated_molecules["26diaminophenol-2cation"]=2
repeated_molecules["4bromonterbutylaniline-neut"]=2
repeated_molecules["4bromonn26tetramethylaniline-cation"]=2
repeated_molecules["4chloroNmethyl2nitroaniline-cation2"]=2
repeated_molecules["246triaminoresorcin-3cation2"]=2
repeated_molecules["246triaminoresorcin-2cation4"]=2
repeated_molecules["246triaminoresorcin-cation2"]=2
repeated_molecules["246triaminoresorcin-2cation6"]=2
repeated_molecules["246triaminoresorcin-cation3"]=2
repeated_molecules["246triaminoresorcin-2cation7"]=2
repeated_molecules["246triaminoresorcin-2cation8"]=2
repeated_molecules["246triaminoresorcin-2cation9"]=2
repeated_molecules["246triaminoresorcin-neut2"]=2
repeated_molecules["246triaminoresorcin-cation7"]=2
repeated_molecules["246triaminoresorcin-cation6"]=2
repeated_molecules["246triaminoresorcin-cation5"]=2
repeated_molecules["246triaminoresorcin-an"]=2
repeated_molecules["246triaminophenol-neut"]=2
repeated_molecules["246triaminophenol-cation*"]=2
repeated_molecules["246triaminophenol-2cation*"]=2
repeated_molecules["246triaminophenol-3cation*"]=2
repeated_molecules["26diclnndime4nitroaniline-cation"]=2
repeated_molecules["26dihydroxyaniline-cation1"]=2
repeated_molecules["26dihydroxyaniline-neut1"]=2
repeated_molecules["26dihydroxyaniline-an1"]=2
repeated_molecules["26dihydroxyaniline-an2"]=2
repeated_molecules["nndiphenylacetamidine-neut*"]=2
repeated_molecules["aminomethyldimethylphenylsilane-cation1"]=2
repeated_molecules["aminomethyldimethylphenylsilane-neut1"]=2
repeated_molecules["aminomethyldimethylphenylsilane-neut2"]=2
repeated_molecules["aminomethyldimethylphenylsilane-neut3"]=2
repeated_molecules["benzyloxymethanimine-cation2"]=2
repeated_molecules["benzyloxymethanimine-neut3"]=2
repeated_molecules["benzyloxymethanimine-neut4"]=2
repeated_molecules["22pdimethylbenzidine-cation"]=2
repeated_molecules["66dime11biphnyl22diamine-cation*"]=2
repeated_molecules["biphenyl44diamino-cation"]=2
repeated_molecules["33pdimethylbenzidine-cation"]=2
repeated_molecules["piperidine1ethyl-neut"]=2
repeated_molecules["piperidine1ethyl-cation"]=2
repeated_molecules["22bipiperidine-cation*"]=2
repeated_molecules["4benzylsulfanylpyridine-cation2"]=2
repeated_molecules["4benzylsulfanylpyridine-neut2"]=2
repeated_molecules["nndimebenzylamine-cation1"]=2
repeated_molecules["nndimebenzylamine-neut1"]=2
repeated_molecules["1cyanomethylpyrrolidine-cation1"]=2
repeated_molecules["1cyanomethylpyrrolidine-neut1"]=2
repeated_molecules["1ptolylpyrrolidine-cation2"]=2
repeated_molecules["nallylmorpholine-cation1"]=2
repeated_molecules["nallylmorpholine-neut1"]=2
repeated_molecules["35dime4nmeampyridine-neut"]=2
repeated_molecules["35dime4nmeampyridine-cation2"]=2
repeated_molecules["46dimepyrimidine-cation"]=2
repeated_molecules["5etnmethypyrimidin2amine-neut"]=2
repeated_molecules["45dime2mercaptopyrimidine-neut"]=2
repeated_molecules["triazine2amino56dimethyl-cation3"]=2
repeated_molecules["135triazine24diamino-cation2"]=2
repeated_molecules["135triazine24diamino-cation3"]=2
repeated_molecules["135triazine24diamino6me-cation2"]=2
repeated_molecules["135triazine24diamino6me-cation3"]=2
repeated_molecules["124triazole35dimethyl-cation1"]=2
repeated_molecules["124triazole35dimethyl-neut1"]=2
repeated_molecules["2dimethylaminobenzimidazole-neut*"]=2
repeated_molecules["2dimethylaminobenzimidazole-cation*"]=2
repeated_molecules["2hydroxybenzimidazole-an1"]=2
repeated_molecules["2hydroxybenzimidazole-neut2"]=2
repeated_molecules["2hydroxybenzimidazole-neut3"]=2
repeated_molecules["bispirine-cation*"]=2
repeated_molecules["bispirine-neut1"]=2
repeated_molecules["2et1hnaphtho23dimidazole-neut*"]=2
repeated_molecules["2dime5678teth1hnaphth23dimidazole-cation3"]=2
repeated_molecules["2dime5678teth1hnaphth23dimidazole-cation4"]=2
repeated_molecules["2dime5678teth1hnaphth23dimidazole-neut"]=2
repeated_molecules["2et5678teth1hnaphth23dimidazole-neut"]=2
repeated_molecules["2oh1hnaphth23dimidazole-an*"]=2
repeated_molecules["2oh1hnaphth23dimidazole-neut2"]=2
repeated_molecules["2oh1hnaphth23dimidazole-neut3"]=2
repeated_molecules["5678teth1hnaphth23dimidazole_neut"]=2
repeated_molecules["5678teth1hnaphth23dimidazole-neut"]=2
repeated_molecules["27diaminophenazine_cation*"]=2
repeated_molecules["4am2chlnmepyrimidin-cation11"]=2
repeated_molecules["4dimeam6chlpyrimidin-cation12"]=2
repeated_molecules["123trimethylguanidine-neut1"]=3
repeated_molecules["1133trimethylguanidine-neut1"]=2
repeated_molecules["ethylhydrazine-cation4"]=2
repeated_molecules["ethylhydrazine-cation5"]=2
repeated_molecules["ethylhydrazine-cation6"]=2
repeated_molecules["ethylhydrazine-cation7"]=2
repeated_molecules["ethylhydrazine-cation8"]=2
repeated_molecules["ethylhydrazine-neut1"]=2
repeated_molecules["ethylhydrazine-neut2"]=4
repeated_molecules["ethylhydrazine-neut3"]=2
repeated_molecules["ethylhydrazine-neut4"]=2
repeated_molecules["ethylhydrazine-neut5"]=2
repeated_molecules["ethylhydrazine-neut6"]=2
repeated_molecules["ethylhydrazine-neut7"]=2
repeated_molecules["ethylhydrazine-neut8"]=2
repeated_molecules["ethylhydrazine-neut9"]=2
repeated_molecules["2am1hnaphth23dimidazol-neut3"]=2
repeated_molecules["2am1hnaphth23dimidazol-neut1"]=2
repeated_molecules["24diam135triazine-cation1"]=2
repeated_molecules["24diam135triazine-cation2"]=2
repeated_molecules["6me24diam135triazine-cation1"]=2
repeated_molecules["6me24diam135triazine-cation2"]=2
repeated_molecules["6meam24diam135triazine-cation10"]=2
repeated_molecules["6meam24diam135triazine-cation11"]=2
repeated_molecules["6meam24diam135triazine-neut"]=2
repeated_molecules["6phenox24diam135triazine_neut"]=2
repeated_molecules["4bromopyrazole-neut"]=2
repeated_molecules["4bromo35dimethylpyrazole-neut"]=2
repeated_molecules["4chlorpyrazole-neut"]=2
repeated_molecules["4methylpyrazole-neut"]=2
repeated_molecules["4bromopyrazole-neut*"]=2
repeated_molecules["4chlor35dimepyrazole-neut*"]=2
repeated_molecules["345trimepyrazole-neut*"]=2
repeated_molecules["6mercapto24diam135triazine-neut2"]=2
repeated_molecules["2me2imidazoline-neut1"]=2
repeated_molecules["2ph2imidazoline-neut"]=2
repeated_molecules["2cl46dimepyrimidine-cation"]=2
repeated_molecules["2oh46dimepyrimidine-neut"]=2
repeated_molecules["6oh24diampyrimidine-neut"]=2
repeated_molecules["2mes46dimepyrimidine-neut*"]=2
repeated_molecules["46dime2meopyrimidine-neut*"]=2
repeated_molecules["5nitropyrimidine-cation*"]=2
repeated_molecules["111f31dimeamethane-neut1"]=2
repeated_molecules["111f31dimeamethane-cation1"]=2
repeated_molecules["cis135triamcyclohexane-2cation1"]=3
repeated_molecules["cis135triamcyclohexane-2cation2"]=6
repeated_molecules["bicyclo221heptane1amino-neut2"]=2 #comprobar
repeated_molecules["bicyclo211hexane1amino-neut2"]=2 #comprobar
repeated_molecules["345trichlorophenol-neut"]=2
repeated_molecules["tetrachloro12benzenediol-an^"]=2   # y borrar repetidos
repeated_molecules["35dicl246trinitrophenol-neut"]=2
repeated_molecules["26dii4nitrophenol-neut*"]=2
repeated_molecules["26dicl4nitrophenol-neut*"]=2
repeated_molecules["26dibr4nitrophenol-neut*"]=2
repeated_molecules["4nitrobenzenethiol-neut*"]=2
repeated_molecules["35diclbenzoic-neut*"]=2
repeated_molecules["26dicl4brphenol-neut*"]=2
repeated_molecules["5me246trinitro13benzenediol-an*"]=2
repeated_molecules["26dime4fphenol-neut*"]=2
repeated_molecules["26dime4brphenol-neut*"]=2
repeated_molecules["4dimeamphenol-neut*"]=2
repeated_molecules["2356tetrame14benzenediol-neut*"]=2
repeated_molecules["2356tetrame14benzenediol-an*"]=4
repeated_molecules["26diiprophenol-neut*"]=2
repeated_molecules["pentafluorobenzoic-neut*"]=2
repeated_molecules["2356tetrafluorobenzoic-neut*"]=2
repeated_molecules["4oh2356tetrafluorobenzoic-neut*"]=2
repeated_molecules["4oh2356tetrafluorobenzoic-an*"]=2
repeated_molecules["4oh35diclbenzenecarbonitrile-neut*"]=2
repeated_molecules["4oh35diclbenzenecarbonitrile-neut*"]=2
repeated_molecules["4me2356tetrafluorobenzoic-neut*"]=2
repeated_molecules["3oh4phcyclobutenedione-neut*"]=2
repeated_molecules["3oh4mecyclobutenedione-neut*"]=2
repeated_molecules["3oh4pohphenylcyclobutenedione-neut*"]=2
repeated_molecules["methanohydroxamic_neut*"]=2
repeated_molecules["2pyrazinecarbohydroxamic-neut*"]=2
repeated_molecules["iprohydroperoxide-neut1"]=2
repeated_molecules["iprohydroperoxide-neut2"]=2
repeated_molecules["iprohydroperoxide-an1"]=2
repeated_molecules["iprohydroperoxide-an2"]=2
repeated_molecules["cyanomelamine-neut1"]=2
repeated_molecules["cyanomelamine-neut3"]=2
repeated_molecules["6thiocian24diam135triazine-cation1"]=2
repeated_molecules["6thiocian24diam135triazine-neut1"]=2
repeated_molecules["2am135triazine-cation2"]=2
repeated_molecules["43dimercapto2am135triazine-neut1"]=2
repeated_molecules["35diam124triazole-neut1"]=2
repeated_molecules["35diam124triazole-cation2"]=2
repeated_molecules["35diam124triazole-cation6"]=2
repeated_molecules["5cl246triampyrimidine-cation1"]=2
repeated_molecules["5br246triampyrimidine-cation2"]=2
repeated_molecules["5nitro246triampyrimidine-cation2"]=2
repeated_molecules["2am45dimeimidazole-neut1"]=2
repeated_molecules["5ipro46diohpyrimidine-neut2"]=2
repeated_molecules["5me46diohpyrimidine-an1"]=2
repeated_molecules["5me46diohpyrimidine-neut7"]=2
repeated_molecules["5me46diohpyrimidine-neut1"]=2
repeated_molecules["5me46diohpyrimidine-neut5"]=2
repeated_molecules["5me46diohpyrimidine-cation*"]=2
repeated_molecules["5me46diohpyrimidine-cation9"]=2
repeated_molecules["5me46diohpyrimidine-cation3"]=2
repeated_molecules["2oh46diampyrimidine-neut*"]=2
repeated_molecules["5me2oh46diampyrimidine-neut*"]=2
repeated_molecules["2mes46diampyrimidne-neut*"]=2
repeated_molecules["5cn2meampyrimidine-neut3"]=2
repeated_molecules["5me246trinitro13benzenediol-an*"]=2
repeated_molecules["5me246trinitro13benzenediol-neut1"]=2
repeated_molecules["fumaric-an*"]=2
repeated_molecules["fumaric-neut*"]=2
repeated_molecules["5cl246trinitrobenzene13diol-an*"]=2
repeated_molecules["5cl246trinitrobenzene13diol-neut3"]=2
repeated_molecules["styphnic-an*"]=2
repeated_molecules["styphnic-neut1"]=2
repeated_molecules["34thiophenedicarboxylic-an*"]=2
repeated_molecules["34thiophenedicarboxylic-neut2"]=2
repeated_molecules["34thiophenedicarboxylic-neut3"]=2
repeated_molecules["34thiophenedicarboxylic-neut10"]=2
repeated_molecules["34thiophenedicarboxylic-neut12"]=2
repeated_molecules["26dicl14benzenediol-an*"]=2
repeated_molecules["26dicl14benzenediol-neut*"]=2
repeated_molecules["2oh5pchlorophenylpyrimidine-neut*"]=2
repeated_molecules["26dicl4ohpyridine-neut2"]=2
repeated_molecules["22diclethanol-an21"]=2
repeated_molecules["22diclethanol-neut11"]=2
repeated_molecules["22diclethanol-neut23"]=2
repeated_molecules["22diclethanol-neut22"]=2
repeated_molecules["22diclethanol-neut21"]=2
repeated_molecules["2clethanol-an21"]=2
repeated_molecules["2clethanol-neut21"]=2
repeated_molecules["2clethanol-neut22"]=2
repeated_molecules["2clethanol-neut23"]=2
repeated_molecules["2clethanol-neut11"]=2
repeated_molecules["biscf3cl3methanol-neut1"]=2
repeated_molecules["14dih4oxo26pyridinecarboxylic-an18"]=2
repeated_molecules["14dih4oxo26pyridinecarboxylic-an2"]=2
repeated_molecules["14dih4oxo26pyridinecarboxylic-an27"]=2
repeated_molecules["14dih4oxo26pyridinecarboxylic-an3"]=2
repeated_molecules["14dih4oxo26pyridinecarboxylic-an13"]=2
repeated_molecules["14dih4oxo26pyridinecarboxylic-an7"]=2
repeated_molecules["14dih4oxo26pyridinecarboxylic-neut18"]=2
repeated_molecules["14dih4oxo26pyridinecarboxylic-neut11"]=2
repeated_molecules["14dih4oxo26pyridinecarboxylic-neut15"]=2
repeated_molecules["14dih4oxo26pyridinecarboxylic-neut21"]=2
repeated_molecules["14dih4oxo26pyridinecarboxylic-neut10"]=2
repeated_molecules["14dih4oxo26pyridinecarboxylic-neut46"]=2
repeated_molecules["14dih4oxo26pyridinecarboxylic-neut43"]=2
repeated_molecules["14dih4oxo26pyridinecarboxylic-neut52"]=2
repeated_molecules["14dih4oxo26pyridinecarboxylic-neut49"]=2
repeated_molecules["14dih4oxo26pyridinecarboxylic-neut33"]=2
repeated_molecules["14dih4oxo26pyridinecarboxylic-neut45"]=2
repeated_molecules["14dih4oxo26pyridinecarboxylic-neut51"]=2
repeated_molecules["14dih4oxo26pyridinecarboxylic-neut35"]=2
repeated_molecules["14dih4oxo26pyridinecarboxylic-neut36"]=2
repeated_molecules["14dih4oxo26pyridinecarboxylic-cation*"]=2
repeated_molecules["phmethanethio-neut11"]=2
repeated_molecules["12diph12ethanedionedioxime-an*"]=2
repeated_molecules["12diph12ethanedionedioxime-neut13"]=2
repeated_molecules["12diph12ethanedionedioxime-neut26"]=2
repeated_molecules["12diph12ethanedionedioxime-neut25"]=2
repeated_molecules["12diph12ethanedionedioxime-neut24"]=2
repeated_molecules["12diph12ethanedionedioxime-neut21"]=2
repeated_molecules["5me123cyclohexatrione13dioxime-neut12"]=2
repeated_molecules["5me123cyclohexatrione13dioxime-neut15"]=2
repeated_molecules["5me123cyclohexatrione13dioxime-neut16"]=2
repeated_molecules["5me123cyclohexatrione13dioxime-neut21"]=2
repeated_molecules["5me123cyclohexatrione13dioxime-neut25"]=2
repeated_molecules["5me123cyclohexatrione13dioxime-an*"]=2
repeated_molecules["S4hydroxyphenylethanethioate-neut*"]=2
repeated_molecules["13indanedione-neut2*"]=2
repeated_molecules["35ditebuphenol-neut11"]=2
repeated_molecules["35ditebuphenol-neut31"]=2
repeated_molecules["35ditebuphenol-an21"]=2
repeated_molecules["4ohbenzenediazonium-cation*"]=2
repeated_molecules["4mercaptobenzoic-an*"]=2
repeated_molecules["nohphthalimide-neut*"]=2
repeated_molecules["4nitroso26dimephenol-neut*"]=2
repeated_molecules["4nitroso35dimethylphenol-neut*"]=2
repeated_molecules["4dimesulfoniophenol-neut*"]=2
repeated_molecules["4dimesulfoniobenzoic-neut*"]=2
repeated_molecules["26ditebupyridine_cation21"]=2
repeated_molecules["26ditebupyridine_neut21"]=2
repeated_molecules["26dimethoxypyridine-cation2*"]=2
repeated_molecules["26dimethoxypyridine-neut2*"]=2
repeated_molecules["pyrazine1oxide-cation2"]=2
repeated_molecules["18naphtalenediol-neut1"]=2
repeated_molecules["18naphtalenediol-an*"]=2
repeated_molecules["2ohme6meophenol-neut21"]=2
repeated_molecules["2ohme6meophenol-neut22"]=2
repeated_molecules["4fnndimebenzylamine-cation1*"]=2
repeated_molecules["4fnndimebenzylamine-neut1*"]=2
repeated_molecules["4nitrodimebenzylamine-cation1*"]=2
repeated_molecules["4nitrodimebenzylamine-neut1*"]=2
repeated_molecules["5ph2ampyrimidine-cation*"]=2
repeated_molecules["12cyclohexanedione-an"]=2
repeated_molecules["45dioh27naphthalenedisulfonic-2an1"]=2
repeated_molecules["45dioh27naphthalenedisulfonic-3an*"]=2
repeated_molecules["35dinitro4oxo14dihpyridine-neut2"]=2
repeated_molecules["246trinitro135benzenetriol-an1"]=6
repeated_molecules["246trinitro135benzenetriol-an3"]=3
repeated_molecules["246trinitro135benzenetriol-an4"]=3
repeated_molecules["246trinitro135benzenetriol-neut1"]=2
repeated_molecules["246trinitro135benzenetriol-neut3"]=6
repeated_molecules["246trinitro13benzenediol-neut1"]=2
repeated_molecules["cis135triamcyclohexane-cation11"]=2
repeated_molecules["cis135triamcyclohexane-cation12"]=2
repeated_molecules["cis135triamcyclohexane-cation22"]=2
repeated_molecules["cis135triamcyclohexane-neut11"]=2
repeated_molecules["cis135triamcyclohexane-neut13"]=6
repeated_molecules["cis135triamcyclohexane-neut41"]=6
repeated_molecules["cis135triamcyclohexane-neut21"]=6 
repeated_molecules["cis135triamcyclohexane-neut12"]=6
repeated_molecules["cis135triamcyclohexane-neut33"]=3
repeated_molecules["cis135triamcyclohexane-neut22"]=3
repeated_molecules["cis135triamcyclohexane-neut32"]=6
repeated_molecules["4cf3sulphonylaniline-cation2*"]=2
repeated_molecules["4cf3sulphonylaniline-neut2*"]=2
repeated_molecules["4clnndimebenzylamine-neut1*"]=2 
repeated_molecules["4clnndimebenzylamine-cation1*"]=2
repeated_molecules["4clnndimebenzylamine-neut3*"]=2
repeated_molecules["4clnndimebenzylamine-neut4*"]=2
repeated_molecules["4clnndimebenzylamine-neut5*"]=2
repeated_molecules["4clnndimebenzylamine-cation3*"]=2
repeated_molecules["4clnndimebenzylamine-cation4*"]=2 
repeated_molecules["4clnndimebenzylamine-cation5*"]=2 
repeated_molecules["5pbrph2ampyrimidine-cation1"]=2
repeated_molecules["45dime2meam5carbamoylpyrimidine-cation1*"]=2
repeated_molecules["45dime2meam5carbamoylpyrimidine-neut*"]=2
repeated_molecules["5ph2meopyrimidine-neut*"]=2
repeated_molecules["5ptolyl2ohpyrimidine-neut*"]=2 
repeated_molecules["5ph2meopyrimidine-neut1"]=2
repeated_molecules["5pfph2meampyrimidine-cation3"]=2
repeated_molecules["5pfph2meampyrimidine-neut1"]=2
repeated_molecules["5ph2meopyrimidine-neut1"]=2
repeated_molecules["5ph4meopyrimidine-neut1"]=2
repeated_molecules["5pfph2ampyrimidine-cation1"]=2 
repeated_molecules["5ptolyl2meampyrimidine-neut1"]=2 
repeated_molecules["5ptolyl2meopyrimidine-neut1"]=2
repeated_molecules["5sulphonic8oh2mequinoline-neut3"]=2
repeated_molecules["6hidrazinoquinoline-2cation34"]=2
repeated_molecules["6meam24diampyrimidine-2cation12"]=2
repeated_molecules["8hidrazinoquinoline-2cation33"]=2
repeated_molecules["8hidrazinoquinoline-2cation12"]=2 
repeated_molecules["8hidrazinoquinoline-2cation31"]=2 
repeated_molecules["8hidrazinoquinoline-cation*"]=2
repeated_molecules["8hidrazinoquinoline-neut*"]=2
repeated_molecules["8meam1imeamnaphthalene-cation*"]=2
repeated_molecules["8oh1oxquinoline-cation2"]=2
repeated_molecules["8oh1oxquinoline-cation3"]=2
repeated_molecules["45dime2meam5carbamoylpyrimidine-neut1"]=2 
repeated_molecules["46dime8mesquinoline-cation1"]=2
repeated_molecules["54nitroph2meampyrimidine-neut1"]=2
repeated_molecules["5pclph2meopyrimidine-neut1"]=2
repeated_molecules["5pbrph2ampyrimidine-cation1"]=2
repeated_molecules["4mesulfonylpyridazine-neut11"]=2 
repeated_molecules["4meoacridine-neut31"]=2 
repeated_molecules["4clnndimebenzylamine-neut11"]=2
repeated_molecules["4clnndimebenzylamine-cation11"]=2
repeated_molecules["3menmeaniline-cation2"]=2
repeated_molecules["3ac4nitroaniline-neut11"]=2
repeated_molecules["3ac4nitroaniline-cation21"]=2
repeated_molecules["2phacetamidine-neut1*"]=2 
repeated_molecules["2phacetamidine-cation1"]=2
repeated_molecules["2oxo46dime1oh12dihpyrimidine-neut5"]=2
repeated_molecules["2oxo46dime1oh12dihpyrimidine-cation1"]=2
repeated_molecules["2meam46dime5cnpyrimidine-neut1"]=2
repeated_molecules["2meam5ipyrimidine-neut1"]=2 
repeated_molecules["2dimeampyrimidine-cation11*"]=2 
repeated_molecules["1me6mes4oxo14dihpyrimidine-neut11"]=2
repeated_molecules["1me6mes4oxo14dihpyrimidine-cation11"]=2
repeated_molecules["hexahydropyrimidine-neut12"]=2
repeated_molecules["hexahydropyrimidine-cation*"]=2
repeated_molecules["2oxo46dime1oh12dihpyrimidine-neut5"]=2
repeated_molecules["5pmeoph2ohpyrimidine-cation1"]=2 
repeated_molecules["2456tetraampyrimidine-cation4"]=2
repeated_molecules["2456tetraampyrimidine-cation6"]=2
repeated_molecules["2456tetraampyrimidine-neut1"]=2
repeated_molecules["6meam9mepurine-cation31"]=2 
repeated_molecules["2oxobutanoic-an2*"]=2
repeated_molecules["2oxobutanoic-neut2*"]=2
repeated_molecules["2propanethiol-neut1"]=2
repeated_molecules["9me2piperidinopurine-cation14"]=2
repeated_molecules["9me2piperidinopurine-cation13"]=2 
repeated_molecules["9me2piperidinopurine-cation12"]=2 
repeated_molecules["9me2piperidinopurine-cation22"]=2 
repeated_molecules["9me2piperidinopurine-cation24"]=2
repeated_molecules["9me2piperidinopurine-neut11"]=2
repeated_molecules["cis10h15naphthyridine-neut1"]=2
repeated_molecules["ethylamethanedithioic-an1"]=2
repeated_molecules["ethylamethanedithioic-neut2"]=2
repeated_molecules["ethylamethanedithioic-neut1"]=2 
repeated_molecules["me2mercaptoacetate-an21"]=2
repeated_molecules["me2mercaptoacetate-neut23"]=2
repeated_molecules["me2mercaptoacetate-neut21"]=2
repeated_molecules["me2mercaptoacetate-neut11"]=2
repeated_molecules["trans10h15naphthyridine-cation1"]=2 
repeated_molecules["trans10h15naphthyridine-cation2"]=2
repeated_molecules["trans10h15naphthyridine-neut2"]=2
repeated_molecules["trans10h18naphthyridine-neut2"]=2
repeated_molecules["11dime1propanethiol-neut1*"]=2 
repeated_molecules["11dime1propanethiol-an1*"]=2
repeated_molecules["cyclohexanephosphonic-an2"]=2
repeated_molecules["cyclohexanephosphonic-an3"]=2
repeated_molecules["cyclohexanephosphonic-an4"]=2 
repeated_molecules["cyclohexanephosphonic-an6"]=2
repeated_molecules["cyclohexanephosphonic-neut52*"]=2
repeated_molecules["cyclohexanephosphonic-neut51*"]=2 
repeated_molecules["cyclohexanephosphonic-neut53*"]=2
repeated_molecules["cyclohexanephosphonic-neut542"]=2
repeated_molecules["cyclohexanephosphonic-neut543"]=2
repeated_molecules["cyclohexanephosphonic-neut551"]=2
repeated_molecules["cyclohexanephosphonic-neut552"]=2
repeated_molecules["cyclohexanephosphonic-neut561"]=2
repeated_molecules["cyclohexanephosphonic-neut563"]=2
repeated_molecules["2me2mercapto1propanol-an2"]=2
repeated_molecules["2me2mercapto1propanol-an1"]=2
repeated_molecules["2me2mercapto1propanol-neut1*"]=2
repeated_molecules["2me2mercapto1propanol-neut22"]=2
repeated_molecules["2me2mercapto1propanol-neut3*"]=2
repeated_molecules["2me2mercapto1propanol-neut4*"]=2
repeated_molecules["2me2mercapto1propanol-neut5*"]=2
repeated_molecules["isopropylidendiphosphonic-2an1*"]=4
repeated_molecules["isopropylidendiphosphonic-2an2*"]=2
repeated_molecules["isopropylidendiphosphonic-3an21"]=4
repeated_molecules["isopropylidendiphosphonic-3an22"]=2
repeated_molecules["isopropylidendiphosphonic-3an13"]=4
repeated_molecules["isopropylidendiphosphonic-an*"]=4
repeated_molecules["diohebutenedioic-neut3"]=2
repeated_molecules["diohebutenedioic-neut2*"]=2
repeated_molecules["diohebutenedioic-2an*"]=2
repeated_molecules["diohebutenedioic-an*"]=2
repeated_molecules["4aminopyridinenoxide-cation*"]=2
repeated_molecules["pclphe246triampyrimidine_cation2"]=2
repeated_molecules["pclphe246triampyrimidine_cation1"]=2
repeated_molecules["bicyclo111pentane1amino-neut*"]=3
repeated_molecules["4dimeabicyclo222oct2carboxylic-neut2"]=2
repeated_molecules["4dimeabicyclo222oct2carboxylic-an2"]=2
repeated_molecules["1naphthylsulfonic-neut2"]=2
repeated_molecules["1naphthylsulfonic-neut"]=2
repeated_molecules["1naphthylsulfonic-neut3"]=2
repeated_molecules["cyclopentylamine-neut"]=2
repeated_molecules["n3dimethylaniline-cation2"]=2
repeated_molecules["n4dimethylaniline-cation1"]=2
repeated_molecules["4methoxypyridineoxide-cation3"]=2
repeated_molecules["2mercaptoethanol-an11"]=2
repeated_molecules["2mercaptoethanol-an11"]=2
repeated_molecules["2mercaptoethanol-an22"]=2
repeated_molecules["2mercaptoethanol-an13"]=2
repeated_molecules["2mercaptoethanol-neut*"]=2 #actually, 2mercaptoethanol-neut51 should not be here, but its energy is quite large
repeated_molecules["nitrooxyacetic-an21"]=2
repeated_molecules["nitrooxyacetic-neut21"]=2
repeated_molecules["nitrooxyacetic-neut22"]=2
repeated_molecules["nitrooxyacetic-neut23"]=2
repeated_molecules["nitrooxyacetic-neut32"]=2
repeated_molecules["5nitro6oh24dione241h3hpyrimidine-neut*"]=2
repeated_molecules["chelidonic-an*"]=2
repeated_molecules["5mesulf1me1h123triazolo45dpyrimidin7one-neut21"]=2
repeated_molecules["5mesulf1me1h123triazolo45dpyrimidin7one-neut22"]=2
repeated_molecules["5mesulf1me1h123triazolo45dpyrimidin7one-neut26"]=2
repeated_molecules["5mesulf1me1h123triazolo45dpyrimidin7one-an21"]=2
repeated_molecules["5mesulf2me1h123triazolo45dpyrimidin7one-an21"]=2
repeated_molecules["5mesulf2me1h123triazolo45dpyrimidin7one-neut21"]=2
repeated_molecules["5mesulf2me1h123triazolo45dpyrimidin7one-neut32"]=2
repeated_molecules["5mesulf2me1h123triazolo45dpyrimidin7one-neut31"]=2
repeated_molecules["5mesulf2me1h123triazolo45dpyrimidin7one-neut26"]=2
repeated_molecules["5mesulf2me1h123triazolo45dpyrimidin7one-neut25"]=2
repeated_molecules["5mesulf2me1h123triazolo45dpyrimidin7one-neut22"]=2
repeated_molecules["cyclohexylmethanidithioic-an11"]=2
repeated_molecules["cyclohexylmethanidithioic-an21"]=2
repeated_molecules["cyclohexylmethanidithioic-neut22"]=2
repeated_molecules["cyclohexylmethanidithioic-neut21"]=2
repeated_molecules["cyclohexylmethanidithioic-neut12"]=2
repeated_molecules["cyclohexylmethanidithioic-neut11"]=2
repeated_molecules["2s5ph6oh23dihpyrimidin41hone-an21"]=2
repeated_molecules["2s5ph6oh23dihpyrimidin41hone-an22"]=2
repeated_molecules["2s5ph6oh23dihpyrimidin41hone-neut*"]=2
repeated_molecules["6oh5phpyrimidine241h3hdione-neut*"]=2
repeated_molecules["13dime6acetoxyampyrimidine24dione-neut2"]=2
repeated_molecules["2ph13indanedione-neut2*"]=2
repeated_molecules["555p5ptetrame22pbipyrrolidine-cation*"]=2
repeated_molecules["435dibr4ohphenyl26dibr25cyclohexadien1oneimino-neut*"]=2
repeated_molecules["5678teth1hnaphthol23dimidazol2one-an*"]=2
repeated_molecules["24clph13indanedione-neut2*"]=2
repeated_molecules["35ditebu4ohbenzoic-an2"]=2
repeated_molecules["2ph13indanedione-neut2*"]=2
repeated_molecules["benzenetriol-neut1"]=2
repeated_molecules["benzenetriol-neut2"]=4
repeated_molecules["benzenetriol-an2"]=2
repeated_molecules["benzenetriol-an3"]=2
repeated_molecules["benzenetriol-an4"]=2
repeated_molecules["benzenetriol-an5"]=2
repeated_molecules["benzenetriol-an6"]=2
repeated_molecules["4benzylpyridine-neut21"]=2
repeated_molecules["4benzylpyridine-cation21"]=2 
repeated_molecules["n2methylpropenylmorpholine-neut*"]=2
repeated_molecules["3ph24pentanedione-an41"]=2
repeated_molecules["3ph24pentanedione-neut*"]=2
repeated_molecules["3me24pentanedione-an41"]=2
repeated_molecules["3me24pentanedione-an31"]=2
repeated_molecules["3me24pentanedione-neut*"]=2
repeated_molecules["transcyclopnt12dicrbxylc4oxo-2an2"]=2
repeated_molecules["transcyclopnt12dicrbxylc4oxo-an*"]=2
repeated_molecules["transcyclopnt12dicrbxylc4oxo-neut10"]=2
repeated_molecules["transcyclopnt12dicrbxylc4oxo-neut2"]=2
repeated_molecules["ocyclohexylurea-cation1"]=2
repeated_molecules["3oh4pohphenylcyclobutenedione-an*"]=2
repeated_molecules["3oh4pohphenylcyclobutenedione-neut*"]=2
repeated_molecules["5cyanocyclopentadiene-neut2"]=2
repeated_molecules["5cyanocyclopentadiene-neut5"]=2
repeated_molecules["dimehtylhydroxylamine-cation2"]=2
repeated_molecules["mehtylhydroxylamine-cation1"]=2
repeated_molecules["5nitro6oh24dione241h3hpyrimidine-2an*"]=2
repeated_molecules["cyanomelamine-an"]=2
repeated_molecules["furantetracarboxylic-2an2001"]=2
repeated_molecules["furantetracarboxylic-2an2002"]=2
repeated_molecules["furantetracarboxylic-2an2003"]=2
repeated_molecules["furantetracarboxylic-2an2004"]=2
repeated_molecules["furantetracarboxylic-2an2005"]=4
repeated_molecules["furantetracarboxylic-2an3002"]=4
repeated_molecules["furantetracarboxylic-neut21100"]=2
repeated_molecules["furantetracarboxylic-neut21101"]=2
repeated_molecules["furantetracarboxylic-neut21102"]=2
repeated_molecules["furantetracarboxylic-neut21103"]=2
repeated_molecules["aadime1piperidineacetonitrile-neut2"]=2
repeated_molecules["aadime1piperidineacetonitrile-cation2"]=2
repeated_molecules["furantetracarboxylic-2an21100"]=2
repeated_molecules["5me13benzenediol-neut11"]=2
repeated_molecules["furantetracarboxylic-neut21100"]=2
repeated_molecules["furantetracarboxylic-neut21101"]=2
repeated_molecules["furantetracarboxylic-neut21102"]=2
repeated_molecules["furantetracarboxylic-neut21103"]=2
repeated_molecules["malononitrile-neut"]=2
repeated_molecules["bromodinitromethane-neut21"]=2
repeated_molecules["bromodinitromethane-neut20"]=2
repeated_molecules["3methyl24pentanedione-neut*"]=2
repeated_molecules["chlorodinitromethane-neut*"]=2
repeated_molecules["2mercaptobenzimidazole-cation*"]=2
repeated_molecules["2hydroxybenzimidazole_cation*"]=2
repeated_molecules["tropone-neut"]=2
repeated_molecules["1me4oxo35dicl14dih-cation*"]=2
repeated_molecules["4clpyridinox-cation2"]=2
repeated_molecules["26dinitro4medimeaniline-cation1"]=2
repeated_molecules["35dibrpyridinox-cation2"]=2
repeated_molecules["35dicl4oxo14dihpyridine_cation*"]=2
repeated_molecules["35diclpyridinox-cation2"]=2
repeated_molecules["1methyl4pyrdoneimine-neut*"]=2
repeated_molecules["246trinitro135benzenetriol-2an*"]=6
repeated_molecules["35dimeindolizine-cation*"]=2
repeated_molecules["5nitro2mepyrimidine-cation*"]=2
repeated_molecules["4chloronndimethylaniline-cation2"]=2 #si se mantiene
repeated_molecules["4aminophenyl4pyridine1oxide-cation5"]=2
repeated_molecules["4aminophenyl4pyridine1oxide-cation2"]=2
repeated_molecules["45diaminoacridine-cation*"] =  2 

repeated_molecules["1r2s3scis1cl23dimecyclpropdicarbxylic-an1000"]=2
repeated_molecules["1r2s3scis1cl23dimecyclpropdicarbxylic-neut1000"]=2
repeated_molecules["24diam6meo135triazine-cation5"]=2
repeated_molecules["24diam6meo135triazine-neut"]=2
repeated_molecules["benzoguanamine-cation2"]=2
repeated_molecules["2mercaptopyrimidine-neut*"]=2
repeated_molecules["chlorotetrazole-neut*"]=2


repeated_molecules["trichloromethylphosphonic-neut*"]=2
repeated_molecules["trichloromethylphosphonic-an"]=2
repeated_molecules["25dimethylpyrrole-cation*"]=2

repeated_molecules["13dime6acetoxyampyrimidine24dione-neut11"]=2
repeated_molecules["13dime6acetoxyampyrimidine24dione-neut10"]=2
repeated_molecules["2356tetracl4ohpyridine-neut100"]=2
repeated_molecules["13naphtalenediol-neut4000"]=2
repeated_molecules["2mes46diampyrimidine-neut*"]=2

repeated_molecules["66diox1me57dihthieno34bpyridin21hone-neut101"]=2

